
export class BaseballPlayer {

    constructor() {
    }

    public getStatsSeasonPipelineBaseball(sportCode: string, playerId: string): any {
        return [
          { $match: { sportCode: sportCode, _id: playerId }, },
          { $unwind: "$games" },
          {
            $group: {
              _id: {
                _id: playerId,
                tidyName: "$tidyName",
                name: "$name",
                teamName: "$teamName",
                season: "$games.season",
              },
              hittingAB: { $sum: "$games.stats.hitting.ab" },
              hittingR: { $sum: "$games.stats.hitting.r" },
              hittingH: { $sum: "$games.stats.hitting.h" },
              hittingRBI: { $sum: "$games.stats.hitting.rbi" },
              hittingDouble: { $sum: "$games.stats.hitting.double" },
              hittingTriple: { $sum: "$games.stats.hitting.triple" },
              hittingHR: { $sum: "$games.stats.hitting.hr" },
              hittingBB: { $max: "$games.stats.hitting.bb" },
              hittingIBB: { $sum: "$games.stats.hitting.ibb" },
              hittingSO: { $sum: "$games.stats.hitting.so" },
              hittingHBP: { $sum: "$games.stats.hitting.hbp" },
              hittingKL: { $sum: "$games.stats.hitting.kl" },
              hittingSB: { $sum: "$games.stats.hitting.sb" },
              hittingCS: { $sum: "$games.stats.hitting.cs" },
              hittingSH: { $sum: "$games.stats.hitting.sh" },
              hittingSF: { $sum: "$games.stats.hitting.sf" },
              hittingPicked: { $sum: "$games.stats.hitting.picked" },
              hittingRCHCI: { $sum: "$games.stats.hitting.rchci" },
              hittingRCHErr: { $sum: "$games.stats.hitting.rcherr" },
              hittingRCHFC: { $sum: "$games.stats.hitting.rchfc" },
              hittingGDP: { $sum: "$games.stats.hitting.gdp" },
              hittingDp: { $sum: "$games.stats.hitting.hitDp" },
              hittingGround: { $sum: "$games.stats.hitting.ground" },
              hittingFly: { $sum: "$games.stats.hitting.fly" },
              fieldingPO: { $sum: "$games.stats.fielding.po" },
              fieldingA: { $sum: "$games.stats.fielding.a" },
              fieldingE: { $sum: "$games.stats.fielding.e" },
              fieldingSBA: { $sum: "$games.stats.fielding.sba" },
              fieldingCSB: { $sum: "$games.stats.fielding.csb" },
              fieldingPB: { $sum: "$games.stats.fielding.pb" },
              fieldingCI: { $sum: "$games.stats.fielding.ci" },
              fieldingIndp: { $sum: "$games.stats.fielding.indp" },
              fieldingIntp: { $sum: "$games.stats.fielding.intp" },
              pitchingWin: { $sum: "$games.stats.pitching.win" },
              pitchingSave: { $sum: "$games.stats.pitching.save" },
              pitchingLoss: { $sum: "$games.stats.pitching.loss" },
              pitchingGS: { $sum: "$games.stats.pitching.gs" },
              pitchingCG: { $sum: "$games.stats.pitching.cg" },
              pitchingSHO: { $sum: "$games.stats.pitching.sho" },
              pitchingCBO: { $sum: "$games.stats.pitching.cbo" },
              pitchingIP: { $sum: "$games.stats.pitching.ip" },
              pitchingH: { $sum: "$games.stats.pitching.h" },
              pitchingR: { $sum: "$games.stats.pitching.r" },
              pitchingER: { $max: "$games.stats.pitching.er" },
              pitchingBB: { $max: "$games.stats.pitching.bb" },
              pitchingK: { $max: "$games.stats.pitching.k" },
              pitchingSO: { $sum: "$games.stats.pitching.so" },
              pitchingBF: { $sum: "$games.stats.pitching.bf" },
              pitchingAB: { $sum: "$games.stats.pitching.ab" },
              pitchingDouble: { $sum: "$games.stats.pitching.double" },
              pitchingTriple: { $sum: "$games.stats.pitching.triple" },
              pitchingHR: { $sum: "$games.stats.pitching.hr" },
              pitchingWP: { $sum: "$games.stats.pitching.wp" },
              pitchingBK: { $sum: "$games.stats.pitching.bk" },
              pitchingHBP: { $sum: "$games.stats.pitching.hbp" },
              pitchingKL: { $sum: "$games.stats.pitching.kl" },
              pitchingIBB: { $sum: "$games.stats.pitching.ibb" },
              pitchingInheritr: { $sum: "$games.stats.pitching.inheritr" },
              pitchingInherits: { $sum: "$games.stats.pitching.inherits" },
              pitchingSFA: { $sum: "$games.stats.pitching.sfa" },
              pitchingSHA: { $sum: "$games.stats.pitching.sha" },
              pitchingCIA: { $sum: "$games.stats.pitching.cia" },
              pitchingPitches: { $sum: "$games.stats.pitching.pitches" },
              pitchingGDP: { $sum: "$games.stats.pitching.gdp" },
              pitchingFly: { $sum: "$games.stats.pitching.fly" },
              pitchingGround: { $sum: "$games.stats.pitching.ground" },
              pitchingTeamUE: { $sum: "$games.stats.pitching.teamue" },
            },
          },
          {
            $project: {
              _id: "$_id._id",
              tidyName: "$_id.tidyName",
              name: "$_id.name",
              teamName: "$_id.teamName",
              season: "$_id.season",
              started: "$_id.started",
              // hitting
              hitting: {
                hittingAB: "$hittingAB",
                hittingR: "$hittingR",
                hittingH: "$hittingH",
                hittingRBI: "$hittingRBI",
                hittingDouble: "$hittingDouble",
                hittingTriple: "$hittingTriple",
                hittingHR: "$hittingHR",
                hittingBB: "$hittingBB",
                hittingIBB: "$hittingIBB",
                hittingSO: "$hittingSO",
                hittingHBP: "$hittingHBP",
                hittingKL: "$hittingKL",
                hittingSB: "$hittingSB",
                hittingCS: "$hittingCS",
                hittingSH: "$hittingSH",
                hittingSF: "$hittingSF",
                hittingPicked: "$hittingPicked",
                hittingRCHCI: "$hittingRCHCI",
                hittingRCHErr: "$hittingRCHErr",
                hittingRCHFC: "$hittingRCHFC",
                hittingGDP: "$hittingGDP",
                hittingDp: "$hittingDp",
                hittingGround: "$hittingGround",
                hittingFly: "$hittingFly",
              },
              // fielding
              fielding: {
                fieldingPO: "$fieldingPO",
                fieldingA: "$fieldingA",
                fieldingE: "$fieldingE",
                fieldingSBA: "$fieldingSBA",
                fieldingCSB: "$fieldingCSB",
                fieldingPB: "$fieldingPB",
                fieldingCI: "$fieldingCI",
                fieldingIndp: "$fieldingIndp",
                fieldingIntp: "$fieldingIntp",
              },
              // pitching
              pitching: {
                pitchingWin: "$pitchingWin",
                pitchingSave: "$pitchingSave",
                pitchingLoss: "$pitchingLoss",
                pitchingGS: "$pitchingGS",
                pitchingCG: "$pitchingCG",
                pitchingSHO: "$pitchingSHO",
                pitchingCBO: "$pitchingCBO",
                pitchingIP: "$pitchingIP",
                pitchingH: "$pitchingH",
                pitchingR: "$pitchingR",
                pitchingER: "$pitchingER",
                pitchingBB: "$pitchingBB",
                pitchingSO: "$pitchingSO",
                pitchingBF: "$pitchingBF",
                pitchingAB: "$pitchingAB",
                pitchingDouble: "$pitchingDouble",
                pitchingTriple: "$pitchingTriple",
                pitchingHR: "$pitchingHR",
                pitchingWP: "$pitchingWP",
                pitchingBK: "$pitchingBK",
                pitchingHBP: "$pitchingHBP",
                pitchingKL: "$pitchingKL",
                pitchingIBB: "$pitchingIBB",
                pitchingInheritr: "$pitchingInheritr",
                pitchingInherits: "$pitchingInherits",
                pitchingSFA: "$pitchingSFA",
                pitchingSHA: "$pitchingSHA",
                pitchingCIA: "$pitchingCIA",
                pitchingPitches: "$pitchingPitches",
                pitchingGDP: "$pitchingGDP",
                pitchingFly: "$pitchingFly",
                pitchingGround: "$pitchingGround",
                pitchingTeamUE: "$pitchingTeamUE",
              },
      
            },
          },
        ];
    }

    public getStatsCareerPipelineBaseball(sportCode: string, playerId: string): any {
        return [
          { $match: { sportCode: sportCode, _id: playerId }, },
          { $unwind: "$games" },
          {
            $group: {
              _id: {
                _id: playerId,
                tidyName: "$tidyName",
                name: "$name",
                teamName: "$teamName",
              },
              hittingAB: { $sum: "$games.stats.hitting.ab" },
              hittingR: { $sum: "$games.stats.hitting.r" },
              hittingH: { $sum: "$games.stats.hitting.h" },
              hittingRBI: { $sum: "$games.stats.hitting.rbi" },
              hittingDouble: { $sum: "$games.stats.hitting.double" },
              hittingTriple: { $sum: "$games.stats.hitting.triple" },
              hittingHR: { $sum: "$games.stats.hitting.hr" },
              hittingBB: { $max: "$games.stats.hitting.bb" },
              hittingIBB: { $sum: "$games.stats.hitting.ibb" },
              hittingSO: { $sum: "$games.stats.hitting.so" },
              hittingHBP: { $sum: "$games.stats.hitting.hbp" },
              hittingKL: { $sum: "$games.stats.hitting.kl" },
              hittingSB: { $sum: "$games.stats.hitting.sb" },
              hittingCS: { $sum: "$games.stats.hitting.cs" },
              hittingSH: { $sum: "$games.stats.hitting.sh" },
              hittingSF: { $sum: "$games.stats.hitting.sf" },
              hittingPicked: { $sum: "$games.stats.hitting.picked" },
              hittingRCHCI: { $sum: "$games.stats.hitting.rchci" },
              hittingRCHErr: { $sum: "$games.stats.hitting.rcherr" },
              hittingRCHFC: { $sum: "$games.stats.hitting.rchfc" },
              hittingGDP: { $sum: "$games.stats.hitting.gdp" },
              hittingDp: { $sum: "$games.stats.hitting.hitDp" },
              hittingGround: { $sum: "$games.stats.hitting.ground" },
              hittingFly: { $sum: "$games.stats.hitting.fly" },
              fieldingPO: { $sum: "$games.stats.fielding.po" },
              fieldingA: { $sum: "$games.stats.fielding.a" },
              fieldingE: { $sum: "$games.stats.fielding.e" },
              fieldingSBA: { $sum: "$games.stats.fielding.sba" },
              fieldingCSB: { $sum: "$games.stats.fielding.csb" },
              fieldingPB: { $sum: "$games.stats.fielding.pb" },
              fieldingCI: { $sum: "$games.stats.fielding.ci" },
              fieldingIndp: { $sum: "$games.stats.fielding.indp" },
              fieldingIntp: { $sum: "$games.stats.fielding.intp" },
              pitchingWin: { $sum: "$games.stats.pitching.win" },
              pitchingSave: { $sum: "$games.stats.pitching.save" },
              pitchingLoss: { $sum: "$games.stats.pitching.loss" },
              pitchingGS: { $sum: "$games.stats.pitching.gs" },
              pitchingCG: { $sum: "$games.stats.pitching.cg" },
              pitchingSHO: { $sum: "$games.stats.pitching.sho" },
              pitchingCBO: { $sum: "$games.stats.pitching.cbo" },
              pitchingIP: { $sum: "$games.stats.pitching.ip" },
              pitchingH: { $sum: "$games.stats.pitching.h" },
              pitchingR: { $sum: "$games.stats.pitching.r" },
              pitchingER: { $max: "$games.stats.pitching.er" },
              pitchingBB: { $max: "$games.stats.pitching.bb" },
              pitchingK: { $max: "$games.stats.pitching.k" },
              pitchingSO: { $sum: "$games.stats.pitching.so" },
              pitchingBF: { $sum: "$games.stats.pitching.bf" },
              pitchingAB: { $sum: "$games.stats.pitching.ab" },
              pitchingDouble: { $sum: "$games.stats.pitching.double" },
              pitchingTriple: { $sum: "$games.stats.pitching.triple" },
              pitchingHR: { $sum: "$games.stats.pitching.hr" },
              pitchingWP: { $sum: "$games.stats.pitching.wp" },
              pitchingBK: { $sum: "$games.stats.pitching.bk" },
              pitchingHBP: { $sum: "$games.stats.pitching.hbp" },
              pitchingKL: { $sum: "$games.stats.pitching.kl" },
              pitchingIBB: { $sum: "$games.stats.pitching.ibb" },
              pitchingInheritr: { $sum: "$games.stats.pitching.inheritr" },
              pitchingInherits: { $sum: "$games.stats.pitching.inherits" },
              pitchingSFA: { $sum: "$games.stats.pitching.sfa" },
              pitchingSHA: { $sum: "$games.stats.pitching.sha" },
              pitchingCIA: { $sum: "$games.stats.pitching.cia" },
              pitchingPitches: { $sum: "$games.stats.pitching.pitches" },
              pitchingGDP: { $sum: "$games.stats.pitching.gdp" },
              pitchingFly: { $sum: "$games.stats.pitching.fly" },
              pitchingGround: { $sum: "$games.stats.pitching.ground" },
              pitchingTeamUE: { $sum: "$games.stats.pitching.teamue" },
            },
          },
          {
            $project: {
              _id: "$_id._id",
              tidyName: "$_id.tidyName",
              name: "$_id.name",
              teamName: "$_id.teamName",
              season: "$_id.season",
              // hitting
              hitting: {
                hittingAB: "$hittingAB",
                hittingR: "$hittingR",
                hittingH: "$hittingH",
                hittingRBI: "$hittingRBI",
                hittingDouble: "$hittingDouble",
                hittingTriple: "$hittingTriple",
                hittingHR: "$hittingHR",
                hittingBB: "$hittingBB",
                hittingIBB: "$hittingIBB",
                hittingSO: "$hittingSO",
                hittingHBP: "$hittingHBP",
                hittingKL: "$hittingKL",
                hittingSB: "$hittingSB",
                hittingCS: "$hittingCS",
                hittingSH: "$hittingSH",
                hittingSF: "$hittingSF",
                hittingPicked: "$hittingPicked",
                hittingRCHCI: "$hittingRCHCI",
                hittingRCHErr: "$hittingRCHErr",
                hittingRCHFC: "$hittingRCHFC",
                hittingGDP: "$hittingGDP",
                hittingDp: "$hittingDp",
                hittingGround: "$hittingGround",
                hittingFly: "$hittingFly",
              },
              // fielding
              fielding: {
                fieldingPO: "$fieldingPO",
                fieldingA: "$fieldingA",
                fieldingE: "$fieldingE",
                fieldingSBA: "$fieldingSBA",
                fieldingCSB: "$fieldingCSB",
                fieldingPB: "$fieldingPB",
                fieldingCI: "$fieldingCI",
                fieldingIndp: "$fieldingIndp",
                fieldingIntp: "$fieldingIntp",
              },
              // pitching
              pitching: {
                pitchingWin: "$pitchingWin",
                pitchingSave: "$pitchingSave",
                pitchingLoss: "$pitchingLoss",
                pitchingGS: "$pitchingGS",
                pitchingCG: "$pitchingCG",
                pitchingSHO: "$pitchingSHO",
                pitchingCBO: "$pitchingCBO",
                pitchingIP: "$pitchingIP",
                pitchingH: "$pitchingH",
                pitchingR: "$pitchingR",
                pitchingER: "$pitchingER",
                pitchingBB: "$pitchingBB",
                pitchingSO: "$pitchingSO",
                pitchingBF: "$pitchingBF",
                pitchingAB: "$pitchingAB",
                pitchingDouble: "$pitchingDouble",
                pitchingTriple: "$pitchingTriple",
                pitchingHR: "$pitchingHR",
                pitchingWP: "$pitchingWP",
                pitchingBK: "$pitchingBK",
                pitchingHBP: "$pitchingHBP",
                pitchingKL: "$pitchingKL",
                pitchingIBB: "$pitchingIBB",
                pitchingInheritr: "$pitchingInheritr",
                pitchingInherits: "$pitchingInherits",
                pitchingSFA: "$pitchingSFA",
                pitchingSHA: "$pitchingSHA",
                pitchingCIA: "$pitchingCIA",
                pitchingPitches: "$pitchingPitches",
                pitchingGDP: "$pitchingGDP",
                pitchingFly: "$pitchingFly",
                pitchingGround: "$pitchingGround",
                pitchingTeamUE: "$pitchingTeamUE",
              },
      
            },
          },
        ];
    }

    public getStatsGamePipelineBaseball(sportCode: string, playerId: string): any {
        return [
          { $match: { sportCode: sportCode, _id: playerId }, },
          { $unwind: "$games" },
          {
            $group: {
              _id: {
                _id: playerId,
                tidyName: "$tidyName",
                name: "$name",
                teamName: "$teamName",
                season: "$games.season",
                gameId: "$games.gameId",
                gameDate: "$games.actualDate",
                opponentName: "$games.opponentName",
              },
              opponentCode: { $first: "$games.opponentCode" },
              hittingAB: { $sum: "$games.stats.hitting.ab" },
              hittingR: { $sum: "$games.stats.hitting.r" },
              hittingH: { $sum: "$games.stats.hitting.h" },
              hittingRBI: { $sum: "$games.stats.hitting.rbi" },
              hittingDouble: { $sum: "$games.stats.hitting.double" },
              hittingTriple: { $sum: "$games.stats.hitting.triple" },
              hittingHR: { $sum: "$games.stats.hitting.hr" },
              hittingBB: { $max: "$games.stats.hitting.bb" },
              hittingIBB: { $sum: "$games.stats.hitting.ibb" },
              hittingSO: { $sum: "$games.stats.hitting.so" },
              hittingHBP: { $sum: "$games.stats.hitting.hbp" },
              hittingKL: { $sum: "$games.stats.hitting.kl" },
              hittingSB: { $sum: "$games.stats.hitting.sb" },
              hittingCS: { $sum: "$games.stats.hitting.cs" },
              hittingSH: { $sum: "$games.stats.hitting.sh" },
              hittingSF: { $sum: "$games.stats.hitting.sf" },
              hittingPicked: { $sum: "$games.stats.hitting.picked" },
              hittingRCHCI: { $sum: "$games.stats.hitting.rchci" },
              hittingRCHErr: { $sum: "$games.stats.hitting.rcherr" },
              hittingRCHFC: { $sum: "$games.stats.hitting.rchfc" },
              hittingGDP: { $sum: "$games.stats.hitting.gdp" },
              hittingDp: { $sum: "$games.stats.hitting.hitDp" },
              hittingGround: { $sum: "$games.stats.hitting.ground" },
              hittingFly: { $sum: "$games.stats.hitting.fly" },
              fieldingPO: { $sum: "$games.stats.fielding.po" },
              fieldingA: { $sum: "$games.stats.fielding.a" },
              fieldingE: { $sum: "$games.stats.fielding.e" },
              fieldingSBA: { $sum: "$games.stats.fielding.sba" },
              fieldingCSB: { $sum: "$games.stats.fielding.csb" },
              fieldingPB: { $sum: "$games.stats.fielding.pb" },
              fieldingCI: { $sum: "$games.stats.fielding.ci" },
              fieldingIndp: { $sum: "$games.stats.fielding.indp" },
              fieldingIntp: { $sum: "$games.stats.fielding.intp" },
              pitchingWin: { $sum: "$games.stats.pitching.win" },
              pitchingSave: { $sum: "$games.stats.pitching.save" },
              pitchingLoss: { $sum: "$games.stats.pitching.loss" },
              pitchingGS: { $sum: "$games.stats.pitching.gs" },
              pitchingCG: { $sum: "$games.stats.pitching.cg" },
              pitchingSHO: { $sum: "$games.stats.pitching.sho" },
              pitchingCBO: { $sum: "$games.stats.pitching.cbo" },
              pitchingIP: { $sum: "$games.stats.pitching.ip" },
              pitchingH: { $sum: "$games.stats.pitching.h" },
              pitchingR: { $sum: "$games.stats.pitching.r" },
              pitchingER: { $max: "$games.stats.pitching.er" },
              pitchingBB: { $max: "$games.stats.pitching.bb" },
              pitchingK: { $max: "$games.stats.pitching.k" },
              pitchingSO: { $sum: "$games.stats.pitching.so" },
              pitchingBF: { $sum: "$games.stats.pitching.bf" },
              pitchingAB: { $sum: "$games.stats.pitching.ab" },
              pitchingDouble: { $sum: "$games.stats.pitching.double" },
              pitchingTriple: { $sum: "$games.stats.pitching.triple" },
              pitchingHR: { $sum: "$games.stats.pitching.hr" },
              pitchingWP: { $sum: "$games.stats.pitching.wp" },
              pitchingBK: { $sum: "$games.stats.pitching.bk" },
              pitchingHBP: { $sum: "$games.stats.pitching.hbp" },
              pitchingKL: { $sum: "$games.stats.pitching.kl" },
              pitchingIBB: { $sum: "$games.stats.pitching.ibb" },
              pitchingInheritr: { $sum: "$games.stats.pitching.inheritr" },
              pitchingInherits: { $sum: "$games.stats.pitching.inherits" },
              pitchingSFA: { $sum: "$games.stats.pitching.sfa" },
              pitchingSHA: { $sum: "$games.stats.pitching.sha" },
              pitchingCIA: { $sum: "$games.stats.pitching.cia" },
              pitchingPitches: { $sum: "$games.stats.pitching.pitches" },
              pitchingGDP: { $sum: "$games.stats.pitching.gdp" },
              pitchingFly: { $sum: "$games.stats.pitching.fly" },
              pitchingGround: { $sum: "$games.stats.pitching.ground" },
              pitchingTeamUE: { $sum: "$games.stats.pitching.teamue" },
            },
          },
          {
            $project: {
              _id: "$_id.gameId",
              tidyName: "$_id.tidyName",
              name: "$_id.name",
              teamName: "$_id.teamName",
              gameDate: "$_id.gameDate",
              opponentName: "$_id.opponentName",
              opponentCode: "$opponentCode",
              season: "$_id.season",
              // hitting
              hitting: {
                hittingAB: "$hittingAB",
                hittingR: "$hittingR",
                hittingH: "$hittingH",
                hittingRBI: "$hittingRBI",
                hittingDouble: "$hittingDouble",
                hittingTriple: "$hittingTriple",
                hittingHR: "$hittingHR",
                hittingBB: "$hittingBB",
                hittingIBB: "$hittingIBB",
                hittingSO: "$hittingSO",
                hittingHBP: "$hittingHBP",
                hittingKL: "$hittingKL",
                hittingSB: "$hittingSB",
                hittingCS: "$hittingCS",
                hittingSH: "$hittingSH",
                hittingSF: "$hittingSF",
                hittingPicked: "$hittingPicked",
                hittingRCHCI: "$hittingRCHCI",
                hittingRCHErr: "$hittingRCHErr",
                hittingRCHFC: "$hittingRCHFC",
                hittingGDP: "$hittingGDP",
                hittingDp: "$hittingDp",
                hittingGround: "$hittingGround",
                hittingFly: "$hittingFly",
              },
              // fielding
              fielding: {
                fieldingPO: "$fieldingPO",
                fieldingA: "$fieldingA",
                fieldingE: "$fieldingE",
                fieldingSBA: "$fieldingSBA",
                fieldingCSB: "$fieldingCSB",
                fieldingPB: "$fieldingPB",
                fieldingCI: "$fieldingCI",
                fieldingIndp: "$fieldingIndp",
                fieldingIntp: "$fieldingIntp",
              },
              // pitching
              pitching: {
                pitchingWin: "$pitchingWin",
                pitchingSave: "$pitchingSave",
                pitchingLoss: "$pitchingLoss",
                pitchingGS: "$pitchingGS",
                pitchingCG: "$pitchingCG",
                pitchingSHO: "$pitchingSHO",
                pitchingCBO: "$pitchingCBO",
                pitchingIP: "$pitchingIP",
                pitchingH: "$pitchingH",
                pitchingR: "$pitchingR",
                pitchingER: "$pitchingER",
                pitchingBB: "$pitchingBB",
                pitchingSO: "$pitchingSO",
                pitchingBF: "$pitchingBF",
                pitchingAB: "$pitchingAB",
                pitchingDouble: "$pitchingDouble",
                pitchingTriple: "$pitchingTriple",
                pitchingHR: "$pitchingHR",
                pitchingWP: "$pitchingWP",
                pitchingBK: "$pitchingBK",
                pitchingHBP: "$pitchingHBP",
                pitchingKL: "$pitchingKL",
                pitchingIBB: "$pitchingIBB",
                pitchingInheritr: "$pitchingInheritr",
                pitchingInherits: "$pitchingInherits",
                pitchingSFA: "$pitchingSFA",
                pitchingSHA: "$pitchingSHA",
                pitchingCIA: "$pitchingCIA",
                pitchingPitches: "$pitchingPitches",
                pitchingGDP: "$pitchingGDP",
                pitchingFly: "$pitchingFly",
                pitchingGround: "$pitchingGround",
                pitchingTeamUE: "$pitchingTeamUE",
              },
      
            },
          },
        ];
    }
}