
export class FootballPlayer {

    constructor() {
    }

    public getStatsSeasonPipelineFootball(sportCode: string, playerId: string): any {
        return [
          { $match: { sportCode: sportCode, _id: playerId }, },
          { $unwind: "$games" },
          {
            $group: {
              _id: {
                _id: playerId,
                tidyName: "$tidyName",
                name: "$name",
                teamName: "$teamName",
                season: "$games.season",
              },
              passComp: { $sum: "$games.stats.pass.passComp" },
              GP: { "$sum": 1 },
              passAtt: { $sum: "$games.stats.pass.passAtt" },
              passInt: { $sum: "$games.stats.pass.passInt" },
              passYards: { $sum: "$games.stats.pass.passYards" },
              passTd: { $sum: "$games.stats.pass.passTd" },
              passLong: { $max: "$games.stats.pass.passLong" },
              passSacks: { $sum: "$games.stats.pass.passSacks" },
              passSackYards: { $sum: "$games.stats.pass.passSackYards" },
              rushAtt: { $sum: "$games.stats.rushing.rushAtt" },
              rushGain: { $sum: "$games.stats.rushing.rushGain" },
              rushLong: { $max: "$games.stats.rushing.rushLong" },
              rushLoss: { $sum: "$games.stats.rushing.rushLoss" },
              rushTd: { $sum: "$games.stats.rushing.rushTd" },
              rushYards: { $sum: "$games.stats.rushing.rushYards" },
              rcvNum: { $sum: "$games.stats.receiving.rcvNum" },
              rcvYards: { $sum: "$games.stats.receiving.rcvYards" },
              rcvTd: { $sum: "$games.stats.receiving.rcvTd" },
              rcvLong: { $max: "$games.stats.receiving.rcvLong" },
              krNo: { $sum: "$games.stats.kickReceiving.krNo" },
              krYards: { $sum: "$games.stats.kickReceiving.krYards" },
              krTd: { $sum: "$games.stats.kickReceiving.krTd" },
              krLong: { $max: "$games.stats.kickReceiving.krLong" },
              prNo: { $sum: "$games.stats.puntReturn.prNo" },
              prYards: { $sum: "$games.stats.puntReturn.prYards" },
              prTd: { $sum: "$games.stats.puntReturn.prTd" },
              prLong: { $max: "$games.stats.puntReturn.prLong" },
              fgMade: { $sum: "$games.stats.fieldgoal.fgMade" },
              fgAtt: { $sum: "$games.stats.fieldgoal.fgAtt" },
              fgLong: { $max: "$games.stats.fieldgoal.fgLong" },
              fgBlocked: { $sum: "$games.stats.fieldgoal.fgBlocked" },
              kickAtt: { $sum: "$games.stats.pointAfter.kickatt" },
              kickMade: { $sum: "$games.stats.pointAfter.kickmade" },
              puntNum: { $sum: "$games.stats.punt.puntNum" },
              puntYards: { $sum: "$games.stats.punt.puntYards" },
              puntLong: { $max: "$games.stats.punt.puntLong" },
              puntBlocked: { $sum: "$games.stats.punt.puntBlocked" },
              puntTb: { $sum: "$games.stats.punt.puntTb" },
              puntFc: { $sum: "$games.stats.punt.puntFc" },
              puntPlus50: { $sum: "$games.stats.punt.puntPlus50" },
              puntInside20: { $sum: "$games.stats.punt.puntInside20" },
              dSacks: { $sum: "$games.stats.defense.dSacks" },
              dSackUa: { $sum: "$games.stats.defense.dSackUa" },
              dSackA: { $sum: "$games.stats.defense.dSackA" },
              dSackYards: { $sum: "$games.stats.defense.dSackYards" },
              dTackUa: { $sum: "$games.stats.defense.dTackUa" },
              dTackA: { $sum: "$games.stats.defense.dTackA" },
              dTackTot: { $sum: "$games.stats.defense.dTackTot" },
              dInt: { $sum: "$games.stats.defense.dInt" },
              dIntYards: { $sum: "$games.stats.defense.dIntYards" },
              irNo: { $sum: "$games.stats.intReturn.irNo" },
              irYards: { $sum: "$games.stats.intReturn.irYards" },
              irTd: { $sum: "$games.stats.intReturn.irTd" },
              irLong: { $max: "$games.stats.intReturn.irLong" },
              dFf: { $sum: "$games.stats.defense.dFf" },
              dFr: { $sum: "$games.stats.defense.dFr" },
              dFryds: { $sum: "$games.stats.defense.dFryds" },
              dTflua: { $sum: "$games.stats.defense.dTflua" },
              dTfla: { $sum: "$games.stats.defense.dTfla" },
              dTflyds: { $sum: "$games.stats.defense.dTflyds" },
              dQbh: { $sum: "$games.stats.defense.dQbh" },
              dBru: { $sum: "$games.stats.defense.dBru" },
              dblkd: { $sum: "$games.stats.defense.dblkd" },
              dBrup: { $sum: "$games.stats.defense.dBrup" },
              koNum: { $sum: "$games.stats.kickoff.koNum" },
              koOb: { $sum: "$games.stats.kickoff.koOb" },
              koTb: { $sum: "$games.stats.kickoff.koTb" },
              koYards: { $sum: "$games.stats.kickoff.koYards" },
              td: { $sum: "$games.stats.scoring.td" },
              fbTotal: { $sum: "$games.stats.fumbles.fbTotal" },
              fbLost: { $sum: "$games.stats.fumbles.fbLost" },
            },
          },
          {
            $project: {
              _id: "$_id._id",
              tidyName: "$_id.tidyName",
              name: "$_id.name",
              teamName: "$_id.teamName",
              season: "$_id.season",
              // pass
              passing: {
                passComp: "$passComp",
                passAtt: "$passAtt",
                passInt: "$passInt",
                passYards: "$passYards",
                passTd: "$passTd",
                passLong: { $ifNull: ["$passLong", 0] },
                passSacks: "$passSacks",
                passSackYards: "$passSackYards",
                GP: "$GP",
              },
              // rush
              rushing: {
                rushAtt: "$rushAtt",
                rushGain: "$rushGain",
                rushLong: { $ifNull: ["$rushLong", 0] },
                rushLoss: "$rushLoss",
                rushTd: "$rushTd",
                rushYards: "$rushYards",
                GP: "$GP",
              },
              // rcv
              receiving: {
                rcvNum: "$rcvNum",
                rcvYards: "$rcvYards",
                rcvTd: "$rcvTd",
                rcvLong: { $ifNull: ["$rcvLong", 0] },
                GP: "$GP",
              },
              returning: {
                GP: "$GP",
                kickReturn: {
                  krNo: "$krNo",
                  krYards: "$krYards",
                  krTd: "$krTd",
                  krLong: { $ifNull: ["$krLong", 0] },
                },
                puntReturn: {
                  prNo: "$prNo",
                  prYards: "$prYards",
                  prTd: "$prTd",
                  prLong: { $ifNull: ["$prLong", 0] },
                },
              },
              kicking: {
                GP: "$GP",
                fieldgoal: {
                  fgMade: "$fgMade",
                  fgAtt: "$fgAtt",
                  fgLong: { $ifNull: ["$fgLong", 0] },
                  fgBlocked: "$fgBlocked",
                },
                pointAfter: {
                  kickAtt: "$kickAtt",
                  kickMade: "$kickMade",
                },
              },
              punting: {
                GP: "$GP",
                puntNum: "$puntNum",
                puntYards: "$puntYards",
                puntLong: { $ifNull: ["$puntLong", 0] },
                puntBlocked: "$puntBlocked",
                puntTb: "$puntTb",
                puntFc: "$puntFc",
                puntPlus50: "$puntPlus50",
                puntInside20: "$puntInside20",
                kickoff: {
                  koNum: "$koNum",
                  koOb: "$koOb",
                  koTb: "$koTb",
                  koYards: "$koYards",
                },
              },
              defense: {
                GP: "$GP",
                sacks: {
                  dSacks: { $add: ["$dSackUa", { $multiply: [0.5, "$dSackA"] }] },
                  dSackUa: "$dSackUa",
                  dSackA: "$dSackA",
                  dSackYards: "$dSackYards",
                },
                tackles: {
                  dTackUa: "$dTackUa",
                  dTackA: "$dTackA",
                  dTackTot: "$dTackTot",
                  dTfl: { $add: ["$dTflua", { $multiply: [0.5, "$dTfla"] }] },
                  dTflYards: "$dTflyds",
                },
                interceptions: {
                  dInt: "$dInt",
                  dIntYards: "$dIntYards",
                  irNo: "$irNo",
                  irYards: "$irYards",
                  irTd: "$irTd",
                  irLong: { $ifNull: ["$irLong", 0] },
                },
                fumbRecovery: {
                  dFf: "$dFf",
                  dFr: "$dFr",
                  dFryds: "$dFryds",
                  dTflua: "$dTflua",
                  dTfla: "$dTfla",
                  dTflyds: "$dTflyds",
                  td: "$td",
                  fbTotal: "$fbTotal",
                  fbLost: "$fbLost",
                },
                pass: {
                  dQbh: "$dQbh",
                  dBrup: "$dBrup",
                },
                dBru: "$dBru",
                dblkd: "$dblkd",
              },
            },
          },
        ];
    }

    public getStatsGamePipelineFootball(sportCode: string, playerId: string): any {
        return [
          { $match: { sportCode: sportCode, _id: playerId }, },
          { $unwind: "$games" },
          { $unwind: "$games.season" },
          {
            $group: {
              _id: {
                _id: playerId,
                tidyName: "$tidyName",
                teamName: "$teamName",
                season: "$games.season",
                gameId: "$games.gameId",
                gameDate: "$games.actualDate",
                opponentName: "$games.opponentName",
                opponentCode: "$games.opponentCode",
                // pass
                passing: {
                  passComp: { $sum: "$games.stats.pass.passComp" },
                  passAtt: { $sum: "$games.stats.pass.passAtt" },
                  passInt: { $sum: "$games.stats.pass.passInt" },
                  passYards: { $sum: "$games.stats.pass.passYards" },
                  passTd: { $sum: "$games.stats.pass.passTd" },
                  passLong: { $sum: "$games.stats.pass.passLong" },
                  passSacks: { $sum: "$games.stats.pass.passSacks" },
                  passSackYards: { $sum: "$games.stats.pass.passSackYards" },
                },
                // rush
                rushing: {
                  rushAtt: { $sum: "$games.stats.rushing.rushAtt" },
                  rushGain: { $sum: "$games.stats.rushing.rushGain" },
                  rushLong: { $sum: "$games.stats.rushing.rushLong" },
                  rushLoss: { $sum: "$games.stats.rushing.rushLoss" },
                  rushTd: { $sum: "$games.stats.rushing.rushTd" },
                  rushYards: { $sum: "$games.stats.rushing.rushYards" },
                  GP: { "$sum": 1 },
                },
                // rcv
                receiving: {
                  rcvNum: { $sum: "$games.stats.receiving.rcvNum" },
                  rcvYards: { $sum: "$games.stats.receiving.rcvYards" },
                  rcvTd: { $sum: "$games.stats.receiving.rcvTd" },
                  rcvLong: { $sum: "$games.stats.receiving.rcvLong" },
                  GP: { "$sum": 1 },
                },
                returning: {
                  kickReturn: {
                    krNo: { $sum: "$games.stats.kickReceiving.krNo" },
                    krYards: { $sum: "$games.stats.kickReceiving.krYards" },
                    krTd: { $sum: "$games.stats.kickReceiving.krTd" },
                    krLong: { $sum: "$games.stats.kickReceiving.krLong" },
                  },
                  puntReturn: {
                    prNo: { $sum: "$games.stats.puntReturn.prNo" },
                    prYards: { $sum: "$games.stats.puntReturn.prYards" },
                    prTd: { $sum: "$games.stats.puntReturn.prTd" },
                    prLong: { $sum: "$games.stats.puntReturn.prLong" },
                  },
                },
                kicking: {
                  fieldgoal: {
                    fgMade: { $sum: "$games.stats.fieldgoal.fgMade" },
                    fgAtt: { $sum: "$games.stats.fieldgoal.fgAtt" },
                    fgLong: { $sum: "$games.stats.fieldgoal.fgLong" },
                    fgBlocked: { $sum: "$games.stats.fieldgoal.fgBlocked" },
                  },
                  pointAfter: {
                    kickAtt: { $sum: "$games.stats.pointAfter.kickatt" },
                    kickMade: { $sum: "$games.stats.pointAfter.kickmade" },
                  },
                },
                punting: {
                  puntNum: { $sum: "$games.stats.punt.puntNum" },
                  puntYards: { $sum: "$games.stats.punt.puntYards" },
                  puntLong: { $sum: "$games.stats.punt.puntLong" },
                  puntBlocked: { $sum: "$games.stats.punt.puntBlocked" },
                  puntTb: { $sum: "$games.stats.punt.puntTb" },
                  puntFc: { $sum: "$games.stats.punt.puntFc" },
                  puntPlus50: { $sum: "$games.stats.punt.puntPlus50" },
                  puntInside20: { $sum: "$games.stats.punt.puntInside20" },
                  kickoff: {
                    koNum: { $sum: "$games.stats.kickoff.koNum" },
                    koOb: { $sum: "$games.stats.kickoff.koOb" },
                    koTb: { $sum: "$games.stats.kickoff.koTb" },
                    koYards: { $sum: "$games.stats.kickoff.koYards" },
                  }
                },
                defense: {
                  dblkd: { $sum: "$games.stats.defense.dblkd" },
                  sacks: {
                    dSacks: { $add: [{ $sum: "$games.stats.defense.dSackUa" }, { $multiply: [0.5, { $sum: "$games.stats.defense.dSackA" }] }] },
                    dSackUa: { $sum: "$games.stats.defense.dSackUa" },
                    dSackA: { $sum: "$games.stats.defense.dSackA" },
                    dSackYards: { $sum: "$games.stats.defense.dSackYards" },
                  },
                  tackles: {
                    dTackUa: { $sum: "$games.stats.defense.dTackUa" },
                    dTackA: { $sum: "$games.stats.defense.dTackA" },
                    dTackTot: { $sum: "$games.stats.defense.dTackTot" },
                    dTfl: { $add: [{ $sum: "$games.stats.defense.dTflua" }, { $multiply: [0.5, { $sum: "$games.stats.defense.dTfla" }] }] },
                    dTflYards: { $sum: "$games.stats.defense.dTflyds" },
                  },
                  interceptions: {
                    dInt: { $sum: "$games.stats.defense.dInt" },
                    dIntYards: { $sum: "$games.stats.defense.dIntYards" },
                    irNo: { $sum: "$games.stats.intReturn.irNo" },
                    irYards: { $sum: "$games.stats.intReturn.irYards" },
                    irTd: { $sum: "$games.stats.intReturn.irTd" },
                    irLong: { $sum: "$games.stats.intReturn.irLong" },
                  },
                  fumbRecovery: {
                    dFf: { $sum: "$games.stats.defense.dFf" },
                    dFr: { $sum: "$games.stats.defense.dFr" },
                    dFryds: { $sum: "$games.stats.defense.dFryds" },
                    dTflua: { $sum: "$games.stats.defense.dTflua" },
                    dTfla: { $sum: "$games.stats.defense.dTfla" },
                    dTflyds: { $sum: "$games.stats.defense.dTflyds" },
                    td: { $sum: "$games.stats.scoring.td" },
                    fbTotal: { $sum: "$games.stats.fumbles.fbTotal" },
                    fbLost: { $sum: "$games.stats.fumbles.fbLost" },
                  },
                  pass: {
                    dQbh: { $sum: "$games.stats.defense.dQbh" },
                    dBru: { $sum: "$games.stats.defense.dBru" },
                    dBrup: { $sum: "$games.stats.defense.dBrup" },
                    dblkd: { $sum: "$games.stats.defense.dblkd" },
                  }
                },
              },
            },
          },
          {
            $project: {
              _id: "$_id.gameId",
              tidyName: "$_id.tidyName",
              name: "$_id.name",
              teamName: "$_id.teamName",
              gameDate: "$_id.gameDate",
              opponentName: "$_id.opponentName",
              opponentCode: "$_id.opponentCode",
              season: "$_id.season",
              passing: "$_id.passing",
              rushing: "$_id.rushing",
              receiving: "$_id.receiving",
              returning: "$_id.returning",
              kicking: "$_id.kicking",
              punting: "$_id.punting",
              defense: "$_id.defense",
            },
          },
          { $sort: { gameDate: 1 } },
        ];
    }

    public getStatsCareerPipelineFootball(sportCode: string, playerId: string): any {
        return [
          { $match: { sportCode: sportCode, _id: playerId }, },
          { $unwind: "$games" },
          {
            $group: {
              _id: {
                _id: playerId,
                tidyName: "$tidyName",
                name: "$name",
                teamName: "$teamName",
              },
              passComp: { $sum: "$games.stats.pass.passComp" },
              GP: { "$sum": 1 },
              passAtt: { $sum: "$games.stats.pass.passAtt" },
              passInt: { $sum: "$games.stats.pass.passInt" },
              passYards: { $sum: "$games.stats.pass.passYards" },
              passTd: { $sum: "$games.stats.pass.passTd" },
              passLong: { $max: "$games.stats.pass.passLong" },
              passSacks: { $sum: "$games.stats.pass.passSacks" },
              passSackYards: { $sum: "$games.stats.pass.passSackYards" },
              rushAtt: { $sum: "$games.stats.rushing.rushAtt" },
              rushGain: { $sum: "$games.stats.rushing.rushGain" },
              rushLong: { $max: "$games.stats.rushing.rushLong" },
              rushLoss: { $sum: "$games.stats.rushing.rushLoss" },
              rushTd: { $sum: "$games.stats.rushing.rushTd" },
              rushYards: { $sum: "$games.stats.rushing.rushYards" },
              rcvNum: { $sum: "$games.stats.receiving.rcvNum" },
              rcvYards: { $sum: "$games.stats.receiving.rcvYards" },
              rcvTd: { $sum: "$games.stats.receiving.rcvTd" },
              rcvLong: { $max: "$games.stats.receiving.rcvLong" },
              krNo: { $sum: "$games.stats.kickReceiving.krNo" },
              krYards: { $sum: "$games.stats.kickReceiving.krYards" },
              krTd: { $sum: "$games.stats.kickReceiving.krTd" },
              krLong: { $max: "$games.stats.kickReceiving.krLong" },
              prNo: { $sum: "$games.stats.puntReturn.prNo" },
              prYards: { $sum: "$games.stats.puntReturn.prYards" },
              prTd: { $sum: "$games.stats.puntReturn.prTd" },
              prLong: { $max: "$games.stats.puntReturn.prLong" },
              fgMade: { $sum: "$games.stats.fieldgoal.fgMade" },
              fgAtt: { $sum: "$games.stats.fieldgoal.fgAtt" },
              fgLong: { $max: "$games.stats.fieldgoal.fgLong" },
              fgBlocked: { $sum: "$games.stats.fieldgoal.fgBlocked" },
              kickAtt: { $sum: "$games.stats.pointAfter.kickatt" },
              kickMade: { $sum: "$games.stats.pointAfter.kickmade" },
              puntNum: { $sum: "$games.stats.punt.puntNum" },
              puntYards: { $sum: "$games.stats.punt.puntYards" },
              puntLong: { $max: "$games.stats.punt.puntLong" },
              puntBlocked: { $sum: "$games.stats.punt.puntBlocked" },
              puntTb: { $sum: "$games.stats.punt.puntTb" },
              puntFc: { $sum: "$games.stats.punt.puntFc" },
              puntPlus50: { $sum: "$games.stats.punt.puntPlus50" },
              puntInside20: { $sum: "$games.stats.punt.puntInside20" },
              dSacks: { $sum: "$games.stats.defense.dSacks" },
              dSackUa: { $sum: "$games.stats.defense.dSackUa" },
              dSackA: { $sum: "$games.stats.defense.dSackA" },
              dSackYards: { $sum: "$games.stats.defense.dSackYards" },
              dTackUa: { $sum: "$games.stats.defense.dTackUa" },
              dTackA: { $sum: "$games.stats.defense.dTackA" },
              dTackTot: { $sum: "$games.stats.defense.dTackTot" },
              dInt: { $sum: "$games.stats.defense.dInt" },
              dIntYards: { $sum: "$games.stats.defense.dIntYards" },
              dBrup: { $sum: "$games.stats.defense.dBrup" },
              dQbh: { $sum: "$games.stats.defense.dQbh" },
              irNo: { $sum: "$games.stats.intReturn.irNo" },
              irYards: { $sum: "$games.stats.intReturn.irYards" },
              irTd: { $sum: "$games.stats.intReturn.irTd" },
              irLong: { $max: "$games.stats.intReturn.irLong" },
              dFf: { $sum: "$games.stats.defense.dFf" },
              dFr: { $sum: "$games.stats.defense.dFr" },
              dFryds: { $sum: "$games.stats.defense.dFryds" },
              dTflua: { $sum: "$games.stats.defense.dTflua" },
              dTfla: { $sum: "$games.stats.defense.dTfla" },
              dTflyds: { $sum: "$games.stats.defense.dTflyds" },
              dBru: { $sum: "$games.stats.defense.dBru" },
              dblkd: { $sum: "$games.stats.defense.dblkd" },
              koNum: { $sum: "$games.stats.kickoff.koNum" },
              koOb: { $sum: "$games.stats.kickoff.koOb" },
              koTb: { $sum: "$games.stats.kickoff.koTb" },
              koYards: { $sum: "$games.stats.kickoff.koYards" },
              td: { $sum: "$games.stats.scoring.td" },
              fbTotal: { $sum: "$games.stats.fumbles.fbTotal" },
              fbLost: { $sum: "$games.stats.fumbles.fbLost" },
            },
          },
          {
            $project: {
              _id: "$_id._id",
              tidyName: "$_id.tidyName",
              name: "$_id.name",
              teamName: "$_id.teamName",
              // pass
              passing: {
                passComp: "$passComp",
                passAtt: "$passAtt",
                passInt: "$passInt",
                passYards: "$passYards",
                passTd: "$passTd",
                passLong: { $ifNull: ["$passLong", 0] },
                passSacks: "$passSacks",
                passSackYards: "$passSackYards",
                GP: "$GP",
              },
              // rush
              rushing: {
                rushAtt: "$rushAtt",
                rushGain: "$rushGain",
                rushLong: { $ifNull: ["$rushLong", 0] },
                rushLoss: "$rushLoss",
                rushTd: "$rushTd",
                rushYards: "$rushYards",
                GP: "$GP",
              },
              // rcv
              receiving: {
                rcvNum: "$rcvNum",
                rcvYards: "$rcvYards",
                rcvTd: "$rcvTd",
                rcvLong: { $ifNull: ["$rcvLong", 0] },
                GP: "$GP",
              },
              returning: {
                GP: "$GP",
                kickReturn: {
                  krNo: "$krNo",
                  krYards: "$krYards",
                  krTd: "$krTd",
                  krLong: { $ifNull: ["$krLong", 0] },
                },
                puntReturn: {
                  prNo: "$prNo",
                  prYards: "$prYards",
                  prTd: "$prTd",
                  prLong: { $ifNull: ["$prLong", 0] },
                },
              },
              kicking: {
                GP: "$GP",
                fieldgoal: {
                  fgMade: "$fgMade",
                  fgAtt: "$fgAtt",
                  fgLong: { $ifNull: ["$fgLong", 0] },
                  fgBlocked: "$fgBlocked",
                },
                pointAfter: {
                  kickAtt: "$kickAtt",
                  kickMade: "$kickMade",
                },
              },
              punting: {
                GP: "$GP",
                puntNum: "$puntNum",
                puntYards: "$puntYards",
                puntLong: { $ifNull: ["$puntLong", 0] },
                puntBlocked: "$puntBlocked",
                puntTb: "$puntTb",
                puntFc: "$puntFc",
                puntPlus50: "$puntPlus50",
                puntInside20: "$puntInside20",
                kickoff: {
                  koNum: "$koNum",
                  koOb: "$koOb",
                  koTb: "$koTb",
                  koYards: "$koYards",
                },
              },
              defense: {
                GP: "$GP",
                sacks: {
                  dSacks: { $add: ["$dSackUa", { $multiply: [0.5, "$dSackA"] }] },
                  dSackUa: "$dSackUa",
                  dSackA: "$dSackA",
                  dSackYards: "$dSackYards",
                },
                tackles: {
                  dTackUa: "$dTackUa",
                  dTackA: "$dTackA",
                  dTackTot: "$dTackTot",
                  dTfl: { $add: ["$dTflua", { $multiply: [0.5, "$dTfla"] }] },
                  dTflYards: "$dTflyds",
                },
                interceptions: {
                  dInt: "$dInt",
                  dIntYards: "$dIntYards",
                  irNo: "$irNo",
                  irYards: "$irYards",
                  irTd: "$irTd",
                  irLong: { $ifNull: ["$irLong", 0] },
                },
                fumbRecovery: {
                  dFf: "$dFf",
                  dFr: "$dFr",
                  dFryds: "$dFryds",
                  dTflua: "$dTflua",
                  dTfla: "$dTfla",
                  td: "$td",
                  fbTotal: "$fbTotal",
                  fbLost: "$fbLost",
                },
                pass: {
                  dBrup: "$dBrup",
                  dQbh: "$dQbh",
                },
                dBru: "$dBrup",
                dblkd: "$dblkd",
              },
            },
          },
        ];
    }
}