export var projectedFieldsBaseball = {
  "name": "PlayerName",
  "games.gameDate": "GameDate",
  "games.actualDate": "GameDate",
  "games.opponentName": "OppName",
  "games.opponentCode": "OppName",
  "games.season": "Season",
  "games.pos": "POS",
  "games.playerClass": "Class",
  "games.uniform": "Jersey",
  "games.opponentConference": "OppoConference",
  "games.opponentConferenceDivision": "OppoConfDivision",
  "games.stats.hitting.cs": "Caught Stealing",
  "games.stats.hitting.r": "Runs Scored",
  "games.stats.hitting.sb": "Stolen Bases (Steals)",
  "games.stats.hitting.sba": "SBA",
  "games.stats.fielding.a": "Assists",
  "games.stats.fielding.ci": "CIA",
  "games.stats.fielding.e": "Errors",
  "games.stats.fielding.pb": "PBA",
  "games.stats.fielding.po": "Putouts",
  "games.stats.fielding.sba": "SBA",
  "games.stats.hitting.ab": "At Bats",
  "games.stats.hitting.double": "Doubles",
  "games.stats.hitting.hbp": "Hit By Pitch",
  "games.stats.hitting.h": "Hits",
  "games.stats.hitting.hr": "Homeruns",
  "games.stats.hitSummary.lob": "Left on Base",
  "games.stats.hitting.pa": "Plate Appearances",
  "games.stats.hitting.rbi": "RBI",
  "games.stats.hitSummary.rcherr": "Reached Base on Error",
  "games.stats.hitting.single": "Singles",
  "games.stats.hitting.so": "Strikeouts",
  "games.stats.hitting.tb": "Total Bases",
  "games.stats.hitting.triple": "Triples",
  "games.stats.hitting.bb": "Walks",
  "games.stats.pitching.bk": "Balks",
  "games.stats.pitching.bf": "Batters Faced",
  "games.stats.pitching.double": "Doubles Allowed",
  "games.stats.pitching.er": "Earned Runs",
  "games.stats.pitching.gdp": "Ground Ball Double Plays",
  "games.stats.pitching.hbp": "Hit By Pitch",
  "games.stats.pitching.h": "Hits",
  "games.stats.pitching.hr": "Homeruns",
  "games.stats.pitching.ip": "Innings Pitched",
  "games.stats.pitching.r": "Runs",
  "games.stats.pitching.sha": "Sac Bunts",
  "games.stats.pitching.sfa": "Sac Flies",
  "games.stats.pitching.so": "Strikeouts",
  "games.stats.pitching.triple": "Triples",
  "games.stats.pitching.bb": "Walks",
  "games.stats.pitching.wp": "Wild Pitches",
  "games.stats.hitSummary.rbi2Out": "RBI with 2 Outs",
  "games.stats.hitting.sf": "Sacrifice Flies",
  "games.stats.hitting.sh": "Sacrifice Hits (Bunts)",
  "gameDate": "GameDate",
  "actualDate": "GameDate",
  "opponentName": "OppName",
  "opponentCode": "OppName",
  "season": "Season",
  "opponentConference": "OppoConference",
  "opponentConferenceDivision": "OppoConfDivision",
  "totals.hitting.cs": "Caught Stealing",
  "totals.hitting.r": "Runs Scored",
  "totals.hitting.sb": "Stolen Bases (Steals)",
  "totals.hitting.sba": "SBA",
  "totals.fielding.a": "Assists",
  "totals.fielding.ci": "CIA",
  "totals.fielding.e": "Errors",
  "totals.fielding.pb": "PBA",
  "totals.fielding.po": "Putouts",
  "totals.fielding.sba": "SBA",
  "totals.hitting.ab": "At Bats",
  "totals.hitting.double": "Doubles",
  "totals.hitting.hbp": "Hit By Pitch",
  "totals.hitting.h": "Hits",
  "totals.hitting.hr": "Homeruns",
  "totals.hitSummary.lob": "Left on Base",
  "totals.hitting.pa": "Plate Appearances",
  "totals.hitting.rbi": "RBI",
  "totals.hitSummary.rcherr": "Reached Base on Error",
  "totals.hitting.single": "Singles",
  "totals.hitting.so": "Strikeouts",
  "totals.hitting.tb": "Total Bases",
  "totals.hitting.triple": "Triples",
  "totals.hitting.bb": "Walks",
  "totals.pitching.bk": "Balks",
  "totals.pitching.bf": "Batters Faced",
  "totals.pitching.double": "Doubles Allowed",
  "totals.pitching.er": "Earned Runs",
  "totals.pitching.gdp": "Ground Ball Double Plays",
  "totals.pitching.hbp": "Hit By Pitch",
  "totals.pitching.h": "Hits",
  "totals.pitching.hr": "Homeruns",
  "totals.pitching.ip": "Innings Pitched",
  "totals.pitching.r": "Runs",
  "totals.pitching.sha": "Sac Bunts",
  "totals.pitching.sfa": "Sac Flies",
  "totals.pitching.so": "Strikeouts",
  "totals.pitching.triple": "Triples",
  "totals.pitching.bb": "Walks",
  "totals.pitching.wp": "Wild Pitches",
  "totals.hitSummary.rbi2Out": "RBI with 2 Outs",
  "totals.hitting.sf": "Sacrifice Flies",
  "totals.hitting.sh": "Sacrifice Hits (Bunts)",
};
