export var projectedFieldsBasketball = {
  "name": "PlayerName",
  "games.gameDate": "GameDate",
  "games.actualDate": "GameDate",
  "games.opponentName": "OppName",
  "games.opponentCode": "OppName",
  "games.season": "Season",
  "games.pos.dpos": "Defence POS",
  "games.pos.opos": "Offense POS",
  "games.pos.pos": "POS",
  "games.opponentConference": "OppoConference",
  "games.opponentConferenceDivision": "OppoConfDivision",
  "games.stats.tp": "Points Scored",
  "games.stats.ast": "Assists",
  "games.stats.stl": "Steals",
  "games.stats.blk": "Blocks",
  "games.stats.treb": "Total Rebounds",
  "games.stats.fgm": "FG Makes",
  "games.stats.fga": "FG Attempts",
  "games.stats.fgpct": "FG %",
  "games.stats.fgm3": "3PT  Makes",
  "games.stats.fga3": "3PT Attempts",
  "games.stats.fg3pct": "3PT %",
  "games.stats.ftm": "FT Makes",
  "games.stats.fta": "FT Attempts",
  "games.stats.ftpct": "FT %",
  "games.stats.oreb": "Offensive Rebounds",
  "games.stats.dreb": "Defensive Rebounds",
  "games.stats.to": "Turnovers",
  "games.stats.min": "Minutes",
  "games.stats.pf": "Personal Fouls",
  "games.stats.tf": "Technical Fouls",
  "games.stats.dDoubles": "Double Doubles",
  "games.stats.tDoubles": "Triple Doubles",
  "totals.stats.tp": "Points Scored",
  "totals.stats.ast": "Assists",
  "totals.stats.stl": "Steals",
  "totals.stats.blk": "Blocks",
  "totals.stats.treb": "Total Rebounds",
  "totals.stats.fgm": "FG Makes",
  "totals.stats.fga": "FG Attempts",
  "totals.stats.fgpct": "FG %",
  "totals.stats.fgm3": "3PT  Makes",
  "totals.stats.fga3": "3PT Attempts",
  "totals.stats.fg3pct": "3PT %",
  "totals.stats.ftm": "FT Makes",
  "totals.stats.fta": "FT Attempts",
  "totals.stats.ftpct": "FT %",
  "totals.stats.oreb": "Offensive Rebounds",
  "totals.stats.dreb": "Defensive Rebounds",
  "totals.stats.to": "Turnovers",
  "totals.stats.min": "Minutes",
  "totals.stats.pf": "Personal Fouls",
  "totals.stats.tf": "Technical Fouls",
  "started": "Started",
  "games.playerClass": "Class",
  "games.uniform": "Jersey",
  "playerClass": "Class",
  "uniform": "Jersey",
  "games.prdStats.tp": "Points Scored",
  "games.prdStats.ast": "Assists",
  "games.prdStats.stl": "Steals",
  "games.prdStats.blk": "Blocks",
  "games.prdStats.treb": "Total Rebounds",
  "games.prdStats.fgm": "FG Makes",
  "games.prdStats.fga": "FG Attempts",
  "games.prdStats.fgpct": "FG %",
  "games.prdStats.fgm3": "3PT  Makes",
  "games.prdStats.fga3": "3PT Attempts",
  "games.prdStats.fg3pct": "3PT %",
  "games.prdStats.ftm": "FT Makes",
  "games.prdStats.fta": "FT Attempts",
  "games.prdStats.ftpct": "FT %",
  "games.prdStats.oreb": "Offensive Rebounds",
  "games.prdStats.dreb": "Defensive Rebounds",
  "games.prdStats.to": "Turnovers",
  "games.prdStats.min": "Minutes",
  "games.prdStats.pf": "Personal Fouls",
  "games.prdStats.tf": "Technical Fouls",
  "totals.prdStats.tp": "Points Scored",
  "totals.prdStats.ast": "Assists",
  "totals.prdStats.stl": "Steals",
  "totals.prdStats.blk": "Blocks",
  "totals.prdStats.treb": "Total Rebounds",
  "totals.prdStats.fgm": "FG Makes",
  "totals.prdStats.fga": "FG Attempts",
  "totals.prdStats.fgpct": "FG %",
  "totals.prdStats.fgm3": "3PT  Makes",
  "totals.prdStats.fga3": "3PT Attempts",
  "totals.prdStats.fg3pct": "3PT %",
  "totals.prdStats.ftm": "FT Makes",
  "totals.prdStats.fta": "FT Attempts",
  "totals.prdStats.ftpct": "FT %",
  "totals.prdStats.oreb": "Offensive Rebounds",
  "totals.prdStats.dreb": "Defensive Rebounds",
  "totals.prdStats.to": "Turnovers",
  "totals.prdStats.min": "Minutes",
  "totals.prdStats.pf": "Personal Fouls",
  "totals.prdStats.tf": "Technical Fouls",
  "gameDate": "GameDate",
  "actualDate": "GameDate",
  "opponentName": "OppName",
  "opponentCode": "OppName",
  "season": "Season",
  "pos.dpos": "Defence POS",
  "pos.opos": "Offense POS",
  "pos.pos": "POS",
  "opponentConference": "OppoConference",
  "opponentConferenceDivision": "OppoConfDivision",
};
