export var projectedFieldsSoccer = {
  "name": "PlayerName",
  "games.gameDate": "GameDate",
  "games.actualDate": "GameDate",
  "games.opponentName": "OppName",
  "games.opponentCode": "OppName",
  "games.season": "Season",
  "games.pos.dpos": "Defence POS",
  "games.pos.opos": "Offense POS",
  "games.pos.pos": "POS",
  "games.opponentConference":"OppoConference",    
  "games.opponentConferenceDivision":"OppoConfDivision",
  "games.gp":"Games Played",
  "games.gs":"Games Started",
  "games.stats.misc.minutes":"Minutes Played",
  "games.stats.goaltype.fg":"First Goal (of the game)",
  "games.stats.goaltype.ua":"Unassisted Goal",
  "games.stats.goaltype.so":"Shoot Out Goal",
  "games.stats.goaltype.gt":"Game Tying Goal",
  "games.stats.goaltype.gw":"Game Winning Goal",
  "games.stats.goaltype.hat":"Third Goal of the Game",
  "games.stats.goaltype.ot":"Goal in Overtime",
  "games.stats.goalie.ga":"Goals Allowed",
  "games.stats.goalie.saves":"Saves",
  "games.stats.goalie.shutout":"Shut outs",
  "games.stats.goalie.sf":"Shots Faced",
  "games.stats.shots.ps":"Penalty Kicks - G",
  "games.stats.shots.psatt":"Penalty Kicks - Att",
  "games.stats.planty.fouls":"Fouls",
  "games.stats.planty.yellow":"Yellow Card",
  "games.stats.planty.red":"Red Card",
  "games.stats.shots.g":"Goals",
  "games.stats.shots.a":"Assists",
  "games.stats.shots.sh":"Shots",
  "games.stats.shots.sog":"Shots on Goal",
  "totals.otherStats.score":"Total Goals",
  "totals.goaltype.ua":"Unassisted",
  "totals.goaltype.ot":"Overtime",
  "totals.goaltype.fg":"First Goal (of the game)",
  "totals.goaltype.so":"Shoot Out Goal",
  "totals.goaltype.gt":"Game Tying Goal",
  "totals.goaltype.gw":"Game Winning Goal",
  "totals.goaltype.hat":"Third Goal of the Game",
  "totals.misc.dsave":"Saves",
  "totals.otherStats.corners":"Goals off Corner",
  "totals.shots.ps":"Penalty Kick - G",
  "totals.shots.psatt":"Penalty Kick - Att",
  "totals.otherStats.offsides":"Offsides",
  "totals.planty.fouls":"Fouls",
  "totals.planty.yellow":"Yellow Card",
  "totals.planty.red":"Red Card",
  "totals.shots.g":"Goals",
  "totals.shots.sog":"Shots on goal",
  "totals.shots.a":"Assists",
  "games.playerClass": "Class",
  "games.uniform": "Jersey",
  "playerClass": "Class",
  "uniform": "Jersey",
  "gameDate": "GameDate",
  "actualDate": "GameDate",
  "opponentName": "OppName",
  "opponentCode": "OppName",
  "season": "Season",
  "pos.dpos": "Defence POS",
  "pos.opos": "Offense POS",
  "pos.pos": "POS",
  "opponentConference":"OppoConference",    
  "opponentConferenceDivision":"OppoConfDivision",
};
