export var miserables = {
  "data": [
    {
      "name": "BEST",
      "type": "Centriod",
      "isActive": "   ",
      "tackles": 155.7,
      "tfl": 23.2,
      "sacks": 0.5,
      "breakUps": 4.9,
      "statFF": 2.8,
      "statFR": 2.3,
      "statINT": 0.8,
      "statQBH": 19.0,
      "statPB": 0.6,
      "statGP": 37,
      "group": "BEST"
    },
    {
      "name": "BETTER",
      "type": "Centriod",
      "isActive": "   ",
      "tackles": 157.0,
      "tfl": 7.4,
      "sacks": 0.2,
      "breakUps": 18.0,
      "statFF": 1.5,
      "statFR": 1.2,
      "statINT": 5.8,
      "statQBH": 2.1,
      "statPB": 0.4,
      "statGP": 37,
      "group": "BETTER"
    },
    {
      "name": "GOOD",
      "type": "Centriod",
      "isActive": "   ",
      "tackles": 66.0,
      "tfl": 4.2,
      "sacks": 1.3,
      "breakUps": 3.2,
      "statFF": 0.4,
      "statFR": 0.3,
      "statINT": 0.4,
      "statQBH": 2.9,
      "statPB": 0.1,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "ADAMS,JP",
      "type": "Player",
      "isActive": "   ",
      "tackles": 16,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 13,
      "group": "GOOD"
    },
    {
      "name": "ALLEN,JONATHAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 152,
      "tfl": 43,
      "sacks": 5.5,
      "breakUps": 7,
      "statFF": 3,
      "statFR": 3,
      "statINT": 0,
      "statQBH": 26,
      "statPB": 2,
      "statGP": 49,
      "group": "BEST"
    },
    {
      "name": "ANDERS,ERYK",
      "type": "Player",
      "isActive": "Active",
      "tackles": 98,
      "tfl": 23,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 5,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 23,
      "statPB": 0,
      "statGP": 32,
      "group": "BEST"
    },
    {
      "name": "ANDERSON,KEATON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 21,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 13,
      "group": "GOOD"
    },
    {
      "name": "ANDERSON,MARK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 141,
      "tfl": 37,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 5,
      "statFR": 3,
      "statINT": 0,
      "statQBH": 24,
      "statPB": 1,
      "statGP": 45,
      "group": "BEST"
    },
    {
      "name": "ANDERSON,RYAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 127,
      "tfl": 42,
      "sacks": 2,
      "breakUps": 3,
      "statFF": 6,
      "statFR": 6,
      "statINT": 1,
      "statQBH": 24,
      "statPB": 0,
      "statGP": 43,
      "group": "BEST"
    },
    {
      "name": "ANDREWS,CARLOS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 45,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "ARENAS,JAVIER",
      "type": "Player",
      "isActive": "   ",
      "tackles": 154,
      "tfl": 20,
      "sacks": 0,
      "breakUps": 13,
      "statFF": 0,
      "statFR": 0,
      "statINT": 6,
      "statQBH": 8,
      "statPB": 0,
      "statGP": 36,
      "group": "BETTER"
    },
    {
      "name": "AVERETT,ANTHONY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 96,
      "tfl": 5,
      "sacks": 1,
      "breakUps": 16,
      "statFF": 1,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 29,
      "group": "GOOD"
    },
    {
      "name": "BACON,WAINE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 145,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 17,
      "statFF": 2,
      "statFR": 3,
      "statINT": 5,
      "statQBH": 2,
      "statPB": 1,
      "statGP": 24,
      "group": "BETTER"
    },
    {
      "name": "BAILEY,KECALF",
      "type": "Player",
      "isActive": "   ",
      "tackles": 74,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 11,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 28,
      "group": "GOOD"
    },
    {
      "name": "BARRON,MARK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 237,
      "tfl": 15,
      "sacks": 0,
      "breakUps": 22,
      "statFF": 1,
      "statFR": 1,
      "statINT": 12,
      "statQBH": 7,
      "statPB": 0,
      "statGP": 48,
      "group": "BETTER"
    },
    {
      "name": "BATES,TODD",
      "type": "Player",
      "isActive": "   ",
      "tackles": 102,
      "tfl": 13,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 4,
      "statINT": 0,
      "statQBH": 7,
      "statPB": 0,
      "statGP": 35,
      "group": "BEST"
    },
    {
      "name": "BEARDEN,LANE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 13,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "BELUE,DEION",
      "type": "Player",
      "isActive": "   ",
      "tackles": 51,
      "tfl": 7,
      "sacks": 0,
      "breakUps": 9,
      "statFF": 1,
      "statFR": 1,
      "statINT": 3,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "BLACKBURN,DARRELL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 59,
      "tfl": 0,
      "sacks": 12,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 22,
      "group": "GOOD"
    },
    {
      "name": "BODDEN,VANN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 22,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "BOLDEN,HIRCHEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 113,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 16,
      "statFF": 1,
      "statFR": 2,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 39,
      "group": "BETTER"
    },
    {
      "name": "BRITT,JUSTIN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 18,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 1,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "BROWN,ELVERETT",
      "type": "Player",
      "isActive": "   ",
      "tackles": 24,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "BROWN,SHANNON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 70,
      "tfl": 0,
      "sacks": 9,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "BROWN,TONY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 88,
      "tfl": 4,
      "sacks": 0.5,
      "breakUps": 5,
      "statFF": 0,
      "statFR": 0,
      "statINT": 3,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 40,
      "group": "GOOD"
    },
    {
      "name": "BROWN,WILL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 73,
      "tfl": 0,
      "sacks": 7,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "BRYANT,ANTHONY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 119,
      "tfl": 7,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 19,
      "statPB": 0,
      "statGP": 48,
      "group": "GOOD"
    },
    {
      "name": "BRYANT,FERNANDO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 174,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 19,
      "statFF": 0,
      "statFR": 0,
      "statINT": 3,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 41,
      "group": "BETTER"
    },
    {
      "name": "BUCK,HARDIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 18,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "BUCKNER,TYRELL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 52,
      "tfl": 0,
      "sacks": 2,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "BUGGS,ISAIAH",
      "type": "Player",
      "isActive": "   ",
      "tackles": 103,
      "tfl": 22,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 2,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 13,
      "statPB": 0,
      "statGP": 28,
      "group": "BEST"
    },
    {
      "name": "BURTON,KENDRICK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 48,
      "tfl": 0,
      "sacks": 4,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "CARROLL,TRAVIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 114,
      "tfl": 15,
      "sacks": 3,
      "breakUps": 0,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 3,
      "statPB": 1,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "CARTER,JAMIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 46,
      "tfl": 5,
      "sacks": 1,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 6,
      "statPB": 0,
      "statGP": 22,
      "group": "GOOD"
    },
    {
      "name": "CARTER,MARCUS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 84,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 28,
      "group": "GOOD"
    },
    {
      "name": "CARTER,SHYHEIM",
      "type": "Player",
      "isActive": "   ",
      "tackles": 58,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 11,
      "statFF": 1,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "CASTILLE,SIMEON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 176,
      "tfl": 19,
      "sacks": 0,
      "breakUps": 27,
      "statFF": 3,
      "statFR": 3,
      "statINT": 12,
      "statQBH": 5,
      "statPB": 1,
      "statGP": 46,
      "group": "BETTER"
    },
    {
      "name": "CHAPMAN,JOSH",
      "type": "Player",
      "isActive": "   ",
      "tackles": 88,
      "tfl": 19,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 40,
      "group": "GOOD"
    },
    {
      "name": "CHILDRESS,AHMAD",
      "type": "Player",
      "isActive": "   ",
      "tackles": 49,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 14,
      "statPB": 0,
      "statGP": 21,
      "group": "GOOD"
    },
    {
      "name": "CLARK,JEREMY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 86,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 5,
      "statPB": 0,
      "statGP": 41,
      "group": "GOOD"
    },
    {
      "name": "CLINTON-DIX,H",
      "type": "Player",
      "isActive": "   ",
      "tackles": 90,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 8,
      "statFF": 1,
      "statFR": 0,
      "statINT": 5,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 32,
      "group": "GOOD"
    },
    {
      "name": "CODY,TERRENCE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 52,
      "tfl": 13,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 2,
      "statINT": 0,
      "statQBH": 5,
      "statPB": 2,
      "statGP": 24,
      "group": "BEST"
    },
    {
      "name": "COLLINS,LANDON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 175,
      "tfl": 11,
      "sacks": 0,
      "breakUps": 12,
      "statFF": 3,
      "statFR": 3,
      "statINT": 5,
      "statQBH": 4,
      "statPB": 1,
      "statGP": 33,
      "group": "BETTER"
    },
    {
      "name": "COLLINS,MATT",
      "type": "Player",
      "isActive": "   ",
      "tackles": 26,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "CONN,MICKEY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 28,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 21,
      "group": "GOOD"
    },
    {
      "name": "CONSTANT,MARVIN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 69,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 1,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "COPELAND,JOHN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 109,
      "tfl": 0,
      "sacks": 15,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "COX,ADAM",
      "type": "Player",
      "isActive": "   ",
      "tackles": 76,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "CURRY,ERIC",
      "type": "Player",
      "isActive": "   ",
      "tackles": 114,
      "tfl": 0,
      "sacks": 20,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 32,
      "group": "GOOD"
    },
    {
      "name": "DANIEL,DAVID",
      "type": "Player",
      "isActive": "   ",
      "tackles": 48,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 6,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "DANIELS,BROOKS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 234,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 2,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 9,
      "statPB": 0,
      "statGP": 33,
      "group": "GOOD"
    },
    {
      "name": "DAREUS,MARCELL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 71,
      "tfl": 22,
      "sacks": 0,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 20,
      "statPB": 0,
      "statGP": 29,
      "group": "GOOD"
    },
    {
      "name": "DAVIS,DANNY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 22,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "DAVIS,FERNANDO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 58,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 22,
      "group": "GOOD"
    },
    {
      "name": "DAVIS,LUTHER",
      "type": "Player",
      "isActive": "   ",
      "tackles": 47,
      "tfl": 9,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 6,
      "statPB": 0,
      "statGP": 28,
      "group": "GOOD"
    },
    {
      "name": "DAVIS,RAEKWON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 128,
      "tfl": 19,
      "sacks": 1,
      "breakUps": 0,
      "statFF": 1,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 8,
      "statPB": 0,
      "statGP": 31,
      "group": "GOOD"
    },
    {
      "name": "DEADERICK,B",
      "type": "Player",
      "isActive": "   ",
      "tackles": 83,
      "tfl": 15,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 11,
      "statPB": 0,
      "statGP": 36,
      "group": "GOOD"
    },
    {
      "name": "DEPRIEST,TREY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 224,
      "tfl": 23,
      "sacks": 0,
      "breakUps": 5,
      "statFF": 3,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 4,
      "statPB": 0,
      "statGP": 47,
      "group": "BEST"
    },
    {
      "name": "DEVALL,DENZEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 81,
      "tfl": 15,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 2,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 14,
      "statPB": 0,
      "statGP": 40,
      "group": "GOOD"
    },
    {
      "name": "DIAL,QUINTON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 44,
      "tfl": 9,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 16,
      "group": "GOOD"
    },
    {
      "name": "DICKSON,XZAVIER",
      "type": "Player",
      "isActive": "   ",
      "tackles": 81,
      "tfl": 21,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 16,
      "statPB": 0,
      "statGP": 34,
      "group": "GOOD"
    },
    {
      "name": "DIGGS,TREVON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 31,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 9,
      "statFF": 1,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 16,
      "group": "GOOD"
    },
    {
      "name": "DIXON,GERALD",
      "type": "Player",
      "isActive": "   ",
      "tackles": 182,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 25,
      "statFF": 0,
      "statFR": 1,
      "statINT": 3,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 47,
      "group": "BETTER"
    },
    {
      "name": "DIXON,TONY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 249,
      "tfl": 5,
      "sacks": 1,
      "breakUps": 9,
      "statFF": 2,
      "statFR": 0,
      "statINT": 3,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 36,
      "group": "BETTER"
    },
    {
      "name": "DONNELLY,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 86,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 24,
      "group": "GOOD"
    },
    {
      "name": "DUKES,JEFFREY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 109,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 2,
      "statFR": 0,
      "statINT": 4,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 24,
      "group": "GOOD"
    },
    {
      "name": "EDWARDS,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 22,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "ELLIS,VICTOR",
      "type": "Player",
      "isActive": "   ",
      "tackles": 146,
      "tfl": 14,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 2,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 18,
      "statPB": 2,
      "statGP": 32,
      "group": "BEST"
    },
    {
      "name": "EVANS,RASHAAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 152,
      "tfl": 24,
      "sacks": 1.5,
      "breakUps": 5,
      "statFF": 2,
      "statFR": 2,
      "statINT": 0,
      "statQBH": 19,
      "statPB": 0,
      "statGP": 43,
      "group": "BEST"
    },
    {
      "name": "FANNEY,BRANDON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 73,
      "tfl": 14,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 5,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "FEAGIN,MICHAEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 32,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 16,
      "group": "GOOD"
    },
    {
      "name": "FITZPATRICK,M",
      "type": "Player",
      "isActive": "   ",
      "tackles": 171,
      "tfl": 18,
      "sacks": 0,
      "breakUps": 26,
      "statFF": 2,
      "statFR": 0,
      "statINT": 9,
      "statQBH": 4,
      "statPB": 2,
      "statGP": 42,
      "group": "BETTER"
    },
    {
      "name": "FLOYD,LAMONT",
      "type": "Player",
      "isActive": "   ",
      "tackles": 27,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 13,
      "group": "GOOD"
    },
    {
      "name": "FORD,BRAD",
      "type": "Player",
      "isActive": "   ",
      "tackles": 45,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 12,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 15,
      "group": "GOOD"
    },
    {
      "name": "FOSTER,CADE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 21,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 18,
      "group": "GOOD"
    },
    {
      "name": "FOSTER,REUBEN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 220,
      "tfl": 20,
      "sacks": 4,
      "breakUps": 11,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 10,
      "statPB": 0,
      "statGP": 44,
      "group": "GOOD"
    },
    {
      "name": "FOUST,WARREN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 30,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "FRAZIER,JOSHUA",
      "type": "Player",
      "isActive": "   ",
      "tackles": 27,
      "tfl": 3,
      "sacks": 1,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 22,
      "group": "GOOD"
    },
    {
      "name": "FULTON,JOHN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 42,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 9,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 24,
      "group": "GOOD"
    },
    {
      "name": "GARDNER,CHARLES",
      "type": "Player",
      "isActive": "   ",
      "tackles": 49,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 8,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "GARTH,JUWAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 61,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 2,
      "statINT": 0,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "GASTON,WILLIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 164,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 15,
      "statFF": 0,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 32,
      "group": "BETTER"
    },
    {
      "name": "GENTRY,NICK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 44,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 8,
      "statPB": 0,
      "statGP": 26,
      "group": "GOOD"
    },
    {
      "name": "GILBERRY,W",
      "type": "Player",
      "isActive": "   ",
      "tackles": 188,
      "tfl": 67,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 5,
      "statFR": 3,
      "statINT": 0,
      "statQBH": 38,
      "statPB": 0,
      "statGP": 47,
      "group": "BEST"
    },
    {
      "name": "GILBERT,DARIUS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 141,
      "tfl": 7,
      "sacks": 0,
      "breakUps": 8,
      "statFF": 1,
      "statFR": 4,
      "statINT": 1,
      "statQBH": 9,
      "statPB": 0,
      "statGP": 37,
      "group": "BEST"
    },
    {
      "name": "GRAY,ERIC",
      "type": "Player",
      "isActive": "   ",
      "tackles": 31,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "GREEN,ROBBY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 39,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "GREENWOOD,BOBBY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 102,
      "tfl": 26,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 15,
      "statPB": 1,
      "statGP": 43,
      "group": "BEST"
    },
    {
      "name": "GREGORY,JAMES",
      "type": "Player",
      "isActive": "   ",
      "tackles": 83,
      "tfl": 0,
      "sacks": 2,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 32,
      "group": "GOOD"
    },
    {
      "name": "GRIFFIN,CORNELIUS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 115,
      "tfl": 18,
      "sacks": 1,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 2,
      "statINT": 0,
      "statQBH": 18,
      "statPB": 0,
      "statGP": 22,
      "group": "BEST"
    },
    {
      "name": "GRIFFIN,RUDY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 33,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "GRIMES,REGGIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 67,
      "tfl": 11,
      "sacks": 2,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 14,
      "statPB": 0,
      "statGP": 33,
      "group": "GOOD"
    },
    {
      "name": "HALL,LEMANSKI",
      "type": "Player",
      "isActive": "   ",
      "tackles": 184,
      "tfl": 0,
      "sacks": 8,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 44,
      "group": "GOOD"
    },
    {
      "name": "HALL,PRINCE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 152,
      "tfl": 16,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 7,
      "statPB": 0,
      "statGP": 32,
      "group": "BEST"
    },
    {
      "name": "HAMILTON,S",
      "type": "Player",
      "isActive": "   ",
      "tackles": 125,
      "tfl": 18,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 2,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 4,
      "statPB": 0,
      "statGP": 30,
      "group": "GOOD"
    },
    {
      "name": "HAMMOND,SPENCER",
      "type": "Player",
      "isActive": "   ",
      "tackles": 28,
      "tfl": 0,
      "sacks": 2,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "HAND,DA'SHAWN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 71,
      "tfl": 16,
      "sacks": 0.5,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 6,
      "statPB": 0,
      "statGP": 34,
      "group": "GOOD"
    },
    {
      "name": "HARPER,ROMAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 302,
      "tfl": 16,
      "sacks": 0,
      "breakUps": 10,
      "statFF": 5,
      "statFR": 4,
      "statINT": 5,
      "statQBH": 6,
      "statPB": 0,
      "statGP": 49,
      "group": "BEST"
    },
    {
      "name": "HARRIS,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 46,
      "tfl": 9,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 28,
      "group": "GOOD"
    },
    {
      "name": "HARRIS,CRAIG",
      "type": "Player",
      "isActive": "   ",
      "tackles": 19,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 13,
      "group": "GOOD"
    },
    {
      "name": "HARRIS,JERRELL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 59,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 4,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "HARRIS,STEVEN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 40,
      "tfl": 0,
      "sacks": 3,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 18,
      "group": "GOOD"
    },
    {
      "name": "HARRISON,RONNIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 175,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 17,
      "statFF": 1,
      "statFR": 2,
      "statINT": 7,
      "statQBH": 3,
      "statPB": 2,
      "statGP": 42,
      "group": "BETTER"
    },
    {
      "name": "HARRISON,STACY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 110,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 11,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 22,
      "group": "GOOD"
    },
    {
      "name": "HIGGENBOTHAM,C",
      "type": "Player",
      "isActive": "   ",
      "tackles": 16,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "HIGHTOWER,D",
      "type": "Player",
      "isActive": "   ",
      "tackles": 234,
      "tfl": 26,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 2,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 24,
      "statPB": 1,
      "statGP": 44,
      "group": "BEST"
    },
    {
      "name": "HOLCOMBE,KEITH",
      "type": "Player",
      "isActive": "   ",
      "tackles": 71,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 5,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 27,
      "group": "GOOD"
    },
    {
      "name": "HOOD,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 90,
      "tfl": 0,
      "sacks": 12,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 26,
      "group": "GOOD"
    },
    {
      "name": "HORNE,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 41,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "HUBBARD,ADRIAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 77,
      "tfl": 19,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 3,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 8,
      "statPB": 0,
      "statGP": 32,
      "group": "GOOD"
    },
    {
      "name": "HUMPHREY,MARLON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 81,
      "tfl": 7,
      "sacks": 0,
      "breakUps": 13,
      "statFF": 3,
      "statFR": 0,
      "statINT": 5,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 29,
      "group": "BETTER"
    },
    {
      "name": "HUNTER,EDDIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 22,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "IVORY,BRANDON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 62,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 29,
      "group": "GOOD"
    },
    {
      "name": "JACKSON,EDDIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 126,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 11,
      "statFF": 2,
      "statFR": 4,
      "statINT": 9,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 38,
      "group": "BETTER"
    },
    {
      "name": "JACKSON,KAREEM",
      "type": "Player",
      "isActive": "   ",
      "tackles": 159,
      "tfl": 9,
      "sacks": 0,
      "breakUps": 29,
      "statFF": 1,
      "statFR": 1,
      "statINT": 5,
      "statQBH": 1,
      "statPB": 2,
      "statGP": 39,
      "group": "BETTER"
    },
    {
      "name": "JACKSON,KEVIN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 136,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 5,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "JAMES,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 30,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 4,
      "statGP": 23,
      "group": "BEST"
    },
    {
      "name": "JEFFRIES,DAMEIAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 90,
      "tfl": 0,
      "sacks": 8,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 29,
      "group": "GOOD"
    },
    {
      "name": "JENNINGS,A",
      "type": "Player",
      "isActive": "   ",
      "tackles": 86,
      "tfl": 17,
      "sacks": 0,
      "breakUps": 11,
      "statFF": 2,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 13,
      "statPB": 0,
      "statGP": 29,
      "group": "BEST"
    },
    {
      "name": "JOHNS,JIMMY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 17,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "JOHNSON,JARRET",
      "type": "Player",
      "isActive": "   ",
      "tackles": 199,
      "tfl": 25,
      "sacks": 1,
      "breakUps": 3,
      "statFF": 5,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 63,
      "statPB": 1,
      "statGP": 47,
      "group": "BEST"
    },
    {
      "name": "JOHNSON,MARQUIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 89,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 23,
      "statFF": 0,
      "statFR": 1,
      "statINT": 3,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 36,
      "group": "BETTER"
    },
    {
      "name": "JOHNSON,NICO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 160,
      "tfl": 19,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 4,
      "statFR": 1,
      "statINT": 2,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 44,
      "group": "BEST"
    },
    {
      "name": "JOHNSON,RASHAD",
      "type": "Player",
      "isActive": "   ",
      "tackles": 224,
      "tfl": 14,
      "sacks": 0,
      "breakUps": 19,
      "statFF": 5,
      "statFR": 1,
      "statINT": 11,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 44,
      "group": "BETTER"
    },
    {
      "name": "JOHNSON,TOMMY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 122,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 19,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 34,
      "group": "GOOD"
    },
    {
      "name": "JOHNSON,TONY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 33,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 22,
      "group": "GOOD"
    },
    {
      "name": "JONES,CHARLES",
      "type": "Player",
      "isActive": "   ",
      "tackles": 211,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 12,
      "statFF": 6,
      "statFR": 0,
      "statINT": 7,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 33,
      "group": "BETTER"
    },
    {
      "name": "JONES,CHRISTION",
      "type": "Player",
      "isActive": "   ",
      "tackles": 20,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 3,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 15,
      "group": "GOOD"
    },
    {
      "name": "JONES,CYRUS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 106,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 21,
      "statFF": 4,
      "statFR": 2,
      "statINT": 6,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 37,
      "group": "BETTER"
    },
    {
      "name": "JONES,HOOTIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 77,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 1,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 26,
      "group": "GOOD"
    },
    {
      "name": "JONES,JASON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 31,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "JONES,TERRENCE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 107,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 4,
      "statPB": 0,
      "statGP": 35,
      "group": "GOOD"
    },
    {
      "name": "JORDAN,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 33,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "KERLEY,ERIC",
      "type": "Player",
      "isActive": "   ",
      "tackles": 62,
      "tfl": 0,
      "sacks": 1.5,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 26,
      "group": "GOOD"
    },
    {
      "name": "KING,KENNY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 195,
      "tfl": 26,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 2,
      "statFR": 6,
      "statINT": 1,
      "statQBH": 87,
      "statPB": 1,
      "statGP": 45,
      "group": "BEST"
    },
    {
      "name": "KING,TYRONE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 38,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 3,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 24,
      "group": "GOOD"
    },
    {
      "name": "KIRKPATRICK,DRE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 91,
      "tfl": 9,
      "sacks": 0,
      "breakUps": 16,
      "statFF": 3,
      "statFR": 1,
      "statINT": 3,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 32,
      "group": "BETTER"
    },
    {
      "name": "KNIGHT,EZEKIAL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 82,
      "tfl": 13,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 2,
      "statFR": 1,
      "statINT": 2,
      "statQBH": 5,
      "statPB": 0,
      "statGP": 26,
      "group": "GOOD"
    },
    {
      "name": "LAKE,DARREN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 26,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 18,
      "group": "GOOD"
    },
    {
      "name": "LANGHAM,ANTONIO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 142,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 24,
      "statFF": 0,
      "statFR": 0,
      "statINT": 6,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 43,
      "group": "BETTER"
    },
    {
      "name": "LEE,DILLON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 68,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 1,
      "statINT": 3,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 31,
      "group": "GOOD"
    },
    {
      "name": "LEE,DOMINIC",
      "type": "Player",
      "isActive": "   ",
      "tackles": 39,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 26,
      "group": "GOOD"
    },
    {
      "name": "LESTER,ROBERT",
      "type": "Player",
      "isActive": "   ",
      "tackles": 133,
      "tfl": 7,
      "sacks": 0,
      "breakUps": 10,
      "statFF": 1,
      "statFR": 2,
      "statINT": 14,
      "statQBH": 2,
      "statPB": 1,
      "statGP": 42,
      "group": "BETTER"
    },
    {
      "name": "LEWIS,MILO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 94,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 29,
      "statFF": 1,
      "statFR": 1,
      "statINT": 9,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 24,
      "group": "BETTER"
    },
    {
      "name": "LOCKETT,VICTOR",
      "type": "Player",
      "isActive": "   ",
      "tackles": 31,
      "tfl": 0,
      "sacks": 2,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 18,
      "group": "GOOD"
    },
    {
      "name": "LOESCHER,N M",
      "type": "Player",
      "isActive": "   ",
      "tackles": 17,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 18,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "LOESCHER,NM",
      "type": "Player",
      "isActive": "   ",
      "tackles": 60,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 25,
      "statPB": 0,
      "statGP": 26,
      "group": "GOOD"
    },
    {
      "name": "LONDON,ANTONIO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 127,
      "tfl": 0,
      "sacks": 10,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 33,
      "group": "GOOD"
    },
    {
      "name": "LOWERY,WILL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 53,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "MADISON,ANTHONY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 140,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 25,
      "statFF": 0,
      "statFR": 1,
      "statINT": 5,
      "statQBH": 0,
      "statPB": 2,
      "statGP": 44,
      "group": "BETTER"
    },
    {
      "name": "MATIAS-SMITH,G",
      "type": "Player",
      "isActive": "   ",
      "tackles": 139,
      "tfl": 9,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 2,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 40,
      "group": "GOOD"
    },
    {
      "name": "MAYDEN,JARED",
      "type": "Player",
      "isActive": "   ",
      "tackles": 23,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 15,
      "group": "GOOD"
    },
    {
      "name": "MCBRIDE,ROBERTO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 35,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 1,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "MCCLAIN,ROLANDO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 275,
      "tfl": 39,
      "sacks": 0,
      "breakUps": 16,
      "statFF": 1,
      "statFR": 2,
      "statINT": 5,
      "statQBH": 17,
      "statPB": 0,
      "statGP": 39,
      "group": "BEST"
    },
    {
      "name": "MCKINNEY,XAVIER",
      "type": "Player",
      "isActive": "   ",
      "tackles": 81,
      "tfl": 10,
      "sacks": 0,
      "breakUps": 10,
      "statFF": 1,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "MCMILLIAN,MARK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 78,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 16,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 22,
      "group": "GOOD"
    },
    {
      "name": "MENZIE,DEQUAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 74,
      "tfl": 10,
      "sacks": 0,
      "breakUps": 15,
      "statFF": 0,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "MERRITT,MIGUEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 79,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 18,
      "group": "GOOD"
    },
    {
      "name": "MILLER,C",
      "type": "Player",
      "isActive": "   ",
      "tackles": 45,
      "tfl": 18,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 15,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "MILLINER,D",
      "type": "Player",
      "isActive": "   ",
      "tackles": 82,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 16,
      "statFF": 1,
      "statFR": 0,
      "statINT": 4,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 24,
      "group": "BETTER"
    },
    {
      "name": "MILLINER,DEE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 47,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 16,
      "statFF": 1,
      "statFR": 1,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 1,
      "statGP": 11,
      "group": "BETTER"
    },
    {
      "name": "MITCHELL,LIONEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 60,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 0,
      "statINT": 5,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 21,
      "group": "GOOD"
    },
    {
      "name": "MONROE,ARIES",
      "type": "Player",
      "isActive": "   ",
      "tackles": 72,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 18,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "MOORE,KELVIN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 78,
      "tfl": 0,
      "sacks": 8,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 36,
      "group": "GOOD"
    },
    {
      "name": "MOOREHEAD,K",
      "type": "Player",
      "isActive": "   ",
      "tackles": 95,
      "tfl": 10,
      "sacks": 0,
      "breakUps": 5,
      "statFF": 1,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 32,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "MOOREHEAD,KINDAL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 79,
      "tfl": 24,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 4,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 34,
      "statPB": 0,
      "statGP": 24,
      "group": "BEST"
    },
    {
      "name": "MORRIS,MARIO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 46,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "MOSES,DYLAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 116,
      "tfl": 19,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 2,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "MOSLEY,CJ",
      "type": "Player",
      "isActive": "   ",
      "tackles": 319,
      "tfl": 24,
      "sacks": 0,
      "breakUps": 19,
      "statFF": 2,
      "statFR": 1,
      "statINT": 5,
      "statQBH": 14,
      "statPB": 0,
      "statGP": 47,
      "group": "BETTER"
    },
    {
      "name": "MOSLEY,JAMEY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 21,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "MUSTIN,DARREN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 88,
      "tfl": 10,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "MYERS,MICHAEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 71,
      "tfl": 0,
      "sacks": 6,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "MYLES,REGGIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 186,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 13,
      "statFF": 1,
      "statFR": 2,
      "statINT": 9,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 42,
      "group": "BETTER"
    },
    {
      "name": "NUNLEY,JEREMY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 129,
      "tfl": 0,
      "sacks": 16,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 38,
      "group": "GOOD"
    },
    {
      "name": "ODEN,DERRICK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 172,
      "tfl": 0,
      "sacks": 2,
      "breakUps": 9,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 29,
      "group": "GOOD"
    },
    {
      "name": "ODOM,ANTWAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 99,
      "tfl": 17,
      "sacks": 0,
      "breakUps": 5,
      "statFF": 4,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 42,
      "statPB": 2,
      "statGP": 35,
      "group": "BEST"
    },
    {
      "name": "PAGAN,JEOFFREY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 60,
      "tfl": 10,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 5,
      "statPB": 1,
      "statGP": 25,
      "group": "GOOD"
    },
    {
      "name": "PARKER,MATT",
      "type": "Player",
      "isActive": "   ",
      "tackles": 68,
      "tfl": 0,
      "sacks": 2,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 16,
      "group": "GOOD"
    },
    {
      "name": "PATRICK,TANA",
      "type": "Player",
      "isActive": "   ",
      "tackles": 39,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "PAYNE,DA'RON",
      "type": "Player",
      "isActive": "   ",
      "tackles": 102,
      "tfl": 5,
      "sacks": 0.5,
      "breakUps": 5,
      "statFF": 1,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 12,
      "statPB": 0,
      "statGP": 35,
      "group": "GOOD"
    },
    {
      "name": "PEPRAH,CHARLIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 210,
      "tfl": 9,
      "sacks": 0,
      "breakUps": 21,
      "statFF": 4,
      "statFR": 5,
      "statINT": 9,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 49,
      "group": "BETTER"
    },
    {
      "name": "PERRY,NICK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 114,
      "tfl": 7,
      "sacks": 0,
      "breakUps": 10,
      "statFF": 0,
      "statFR": 1,
      "statINT": 2,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 28,
      "group": "GOOD"
    },
    {
      "name": "PETTWAY,DJ",
      "type": "Player",
      "isActive": "   ",
      "tackles": 47,
      "tfl": 12,
      "sacks": 0,
      "breakUps": 5,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 7,
      "statPB": 1,
      "statGP": 27,
      "group": "GOOD"
    },
    {
      "name": "PICKETT,PAUL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 59,
      "tfl": 0,
      "sacks": 3,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 25,
      "group": "GOOD"
    },
    {
      "name": "PINE,MATTHEW",
      "type": "Player",
      "isActive": "   ",
      "tackles": 23,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 18,
      "group": "GOOD"
    },
    {
      "name": "POPE,DERRICK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 171,
      "tfl": 14,
      "sacks": 0,
      "breakUps": 6,
      "statFF": 2,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 8,
      "statPB": 0,
      "statGP": 25,
      "group": "BEST"
    },
    {
      "name": "POWELL,OZELL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 66,
      "tfl": 0,
      "sacks": 5,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 35,
      "group": "GOOD"
    },
    {
      "name": "RAGLAND,REGGIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 215,
      "tfl": 20,
      "sacks": 0,
      "breakUps": 10,
      "statFF": 4,
      "statFR": 3,
      "statINT": 1,
      "statQBH": 5,
      "statPB": 0,
      "statGP": 42,
      "group": "BEST"
    },
    {
      "name": "RASHEED,SALEEM",
      "type": "Player",
      "isActive": "   ",
      "tackles": 298,
      "tfl": 19,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 3,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 15,
      "statPB": 1,
      "statGP": 36,
      "group": "BEST"
    },
    {
      "name": "RAY,LABRYAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 44,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "RAY,SHONTUA",
      "type": "Player",
      "isActive": "   ",
      "tackles": 59,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 1,
      "statGP": 29,
      "group": "GOOD"
    },
    {
      "name": "REAMER,CORY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 90,
      "tfl": 15,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 2,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 4,
      "statPB": 1,
      "statGP": 28,
      "group": "BEST"
    },
    {
      "name": "REED,JARRAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 109,
      "tfl": 12,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 6,
      "statPB": 0,
      "statGP": 28,
      "group": "GOOD"
    },
    {
      "name": "RICHARDSON,T",
      "type": "Player",
      "isActive": "   ",
      "tackles": 13,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "ROACH,FREDDIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 272,
      "tfl": 25,
      "sacks": 0,
      "breakUps": 14,
      "statFF": 6,
      "statFR": 3,
      "statINT": 1,
      "statQBH": 17,
      "statPB": 0,
      "statGP": 49,
      "group": "BEST"
    },
    {
      "name": "ROBINSON,A",
      "type": "Player",
      "isActive": "   ",
      "tackles": 128,
      "tfl": 27,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 18,
      "statPB": 3,
      "statGP": 37,
      "group": "BEST"
    },
    {
      "name": "ROBINSON,RAMZEE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 146,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 22,
      "statFF": 2,
      "statFR": 0,
      "statINT": 4,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 46,
      "group": "BETTER"
    },
    {
      "name": "ROCKWELL,BRAGG",
      "type": "Player",
      "isActive": "   ",
      "tackles": 27,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "ROGERS,CHRIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 43,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 1,
      "statFR": 2,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 30,
      "group": "GOOD"
    },
    {
      "name": "ROGERS,MICHAEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 183,
      "tfl": 0,
      "sacks": 4,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 34,
      "group": "GOOD"
    },
    {
      "name": "ROGERS,MICHAL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 40,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "ROYAL,ANDRE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 79,
      "tfl": 0,
      "sacks": 6,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 28,
      "group": "GOOD"
    },
    {
      "name": "RUDD,DWAYNE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 173,
      "tfl": 0,
      "sacks": 6,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 33,
      "group": "GOOD"
    },
    {
      "name": "RYANS,DEMECO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 307,
      "tfl": 33,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 4,
      "statFR": 5,
      "statINT": 2,
      "statQBH": 12,
      "statPB": 0,
      "statGP": 48,
      "group": "BEST"
    },
    {
      "name": "SAMUEL,CEDRIC",
      "type": "Player",
      "isActive": "   ",
      "tackles": 150,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 32,
      "group": "GOOD"
    },
    {
      "name": "SANDERS,THEO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 20,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "SAUNDERS,KEITH",
      "type": "Player",
      "isActive": "   ",
      "tackles": 60,
      "tfl": 7,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 4,
      "statPB": 0,
      "statGP": 30,
      "group": "GOOD"
    },
    {
      "name": "SCOTT,DAVID",
      "type": "Player",
      "isActive": "   ",
      "tackles": 34,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 16,
      "group": "GOOD"
    },
    {
      "name": " ",
      "type": "Player",
      "isActive": "   ",
      "tackles": 211,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 14,
      "statFF": 0,
      "statFR": 2,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 42,
      "group": "BETTER"
    },
    {
      "name": "SHARRIEF,ALI",
      "type": "Player",
      "isActive": "   ",
      "tackles": 73,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 6,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 6,
      "statPB": 0,
      "statGP": 33,
      "group": "GOOD"
    },
    {
      "name": "SHORT,ANDRE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 99,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 29,
      "group": "GOOD"
    },
    {
      "name": "SIGLER,KELVIN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 155,
      "tfl": 6,
      "sacks": 1,
      "breakUps": 8,
      "statFF": 4,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 2,
      "statPB": 1,
      "statGP": 29,
      "group": "BEST"
    },
    {
      "name": "SIMPSON,JUWAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 182,
      "tfl": 18,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 2,
      "statFR": 1,
      "statINT": 3,
      "statQBH": 12,
      "statPB": 0,
      "statGP": 33,
      "group": "BEST"
    },
    {
      "name": "SMITH,KENNY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 171,
      "tfl": 27,
      "sacks": 2,
      "breakUps": 2,
      "statFF": 3,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 54,
      "statPB": 2,
      "statGP": 38,
      "group": "BEST"
    },
    {
      "name": "SMITH,MAURICE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 38,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 5,
      "statFF": 1,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 21,
      "group": "GOOD"
    },
    {
      "name": "SMITH,SAIVION",
      "type": "Player",
      "isActive": "   ",
      "tackles": 60,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 5,
      "statFF": 1,
      "statFR": 0,
      "statINT": 3,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "SMITH,TITO",
      "type": "Player",
      "isActive": "   ",
      "tackles": 30,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 15,
      "group": "GOOD"
    },
    {
      "name": "SMITH,TREVIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 130,
      "tfl": 15,
      "sacks": 2,
      "breakUps": 5,
      "statFF": 1,
      "statFR": 5,
      "statINT": 0,
      "statQBH": 10,
      "statPB": 0,
      "statGP": 19,
      "group": "BEST"
    },
    {
      "name": "SPENCER,MARCUS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 299,
      "tfl": 15,
      "sacks": 1,
      "breakUps": 12,
      "statFF": 2,
      "statFR": 1,
      "statINT": 10,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 44,
      "group": "BETTER"
    },
    {
      "name": "SQUARE,DAMION",
      "type": "Player",
      "isActive": "   ",
      "tackles": 93,
      "tfl": 22,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 13,
      "statPB": 0,
      "statGP": 36,
      "group": "GOOD"
    },
    {
      "name": "STAMPS,MARCEL",
      "type": "Player",
      "isActive": "   ",
      "tackles": 16,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 2,
      "statGP": 13,
      "group": "GOOD"
    },
    {
      "name": "STANLEY,STEVE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 67,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 5,
      "statPB": 0,
      "statGP": 27,
      "group": "GOOD"
    },
    {
      "name": "STATEN,RALPH",
      "type": "Player",
      "isActive": "   ",
      "tackles": 159,
      "tfl": 0,
      "sacks": 5.5,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 30,
      "group": "GOOD"
    },
    {
      "name": "STEWART,ROBERT",
      "type": "Player",
      "isActive": "   ",
      "tackles": 108,
      "tfl": 0,
      "sacks": 8,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "STINSON,ED",
      "type": "Player",
      "isActive": "   ",
      "tackles": 102,
      "tfl": 18,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 3,
      "statINT": 0,
      "statQBH": 10,
      "statPB": 0,
      "statGP": 40,
      "group": "BEST"
    },
    {
      "name": "SULLINS,JOHN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 149,
      "tfl": 0,
      "sacks": 4,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "SUNSERI,VINNIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 102,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 8,
      "statFF": 1,
      "statFR": 3,
      "statINT": 4,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 27,
      "group": "BETTER"
    },
    {
      "name": "SURTAIN,PATRICK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 32,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 6,
      "statFF": 1,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "SYLVE,BRADLEY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 40,
      "tfl": 1,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 21,
      "group": "GOOD"
    },
    {
      "name": "TANKS,JOHN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 25,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "TAYLOR,LANCE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 14,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 1,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "TEAGUE,GEORGE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 139,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 22,
      "statFF": 0,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 35,
      "group": "BETTER"
    },
    {
      "name": "THOMAS,EFRUM",
      "type": "Player",
      "isActive": "   ",
      "tackles": 52,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 12,
      "group": "GOOD"
    },
    {
      "name": "THOMPSON,D",
      "type": "Player",
      "isActive": "   ",
      "tackles": 92,
      "tfl": 4,
      "sacks": 0,
      "breakUps": 6,
      "statFF": 3,
      "statFR": 1,
      "statINT": 3,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "TOMLINSON,D",
      "type": "Player",
      "isActive": "   ",
      "tackles": 101,
      "tfl": 14,
      "sacks": 0,
      "breakUps": 10,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 11,
      "statPB": 0,
      "statGP": 33,
      "group": "GOOD"
    },
    {
      "name": "TOWNSEND,DESHEA",
      "type": "Player",
      "isActive": "   ",
      "tackles": 139,
      "tfl": 0,
      "sacks": 2,
      "breakUps": 31,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 39,
      "group": "BETTER"
    },
    {
      "name": "TURNER,ERIC",
      "type": "Player",
      "isActive": "   ",
      "tackles": 30,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "UPSHAW,COURTNEY",
      "type": "Player",
      "isActive": "   ",
      "tackles": 141,
      "tfl": 38,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 6,
      "statFR": 3,
      "statINT": 1,
      "statQBH": 18,
      "statPB": 0,
      "statGP": 45,
      "group": "BEST"
    },
    {
      "name": "WAGGONER,CLINT",
      "type": "Player",
      "isActive": "   ",
      "tackles": 34,
      "tfl": 10,
      "sacks": 3,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 12,
      "statPB": 0,
      "statGP": 17,
      "group": "GOOD"
    },
    {
      "name": "WALDROP,D",
      "type": "Player",
      "isActive": "   ",
      "tackles": 72,
      "tfl": 6,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 3,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 3,
      "statPB": 0,
      "statGP": 31,
      "group": "GOOD"
    },
    {
      "name": "WALLACE,LEVI",
      "type": "Player",
      "isActive": "   ",
      "tackles": 59,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 17,
      "statFF": 0,
      "statFR": 0,
      "statINT": 3,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "WALTERS,JOHN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 158,
      "tfl": 0,
      "sacks": 1,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 41,
      "group": "GOOD"
    },
    {
      "name": "WARD,THURMAN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 21,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 1,
      "statFR": 0,
      "statINT": 1,
      "statQBH": 2,
      "statPB": 0,
      "statGP": 16,
      "group": "GOOD"
    },
    {
      "name": "WASHINGTON,ERIC",
      "type": "Player",
      "isActive": "   ",
      "tackles": 20,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 13,
      "group": "GOOD"
    },
    {
      "name": "WASHINGTON,J",
      "type": "Player",
      "isActive": "   ",
      "tackles": 25,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 2,
      "statFF": 0,
      "statFR": 0,
      "statINT": 2,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 18,
      "group": "GOOD"
    },
    {
      "name": "WASHINGTON,L",
      "type": "Player",
      "isActive": "   ",
      "tackles": 70,
      "tfl": 15,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 15,
      "statPB": 1,
      "statGP": 37,
      "group": "GOOD"
    },
    {
      "name": "WATKINS,ALEX",
      "type": "Player",
      "isActive": "   ",
      "tackles": 34,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 1,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 4,
      "statPB": 0,
      "statGP": 21,
      "group": "GOOD"
    },
    {
      "name": "WEBB,STEVE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 69,
      "tfl": 0,
      "sacks": 5,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 0,
      "statGP": 20,
      "group": "GOOD"
    },
    {
      "name": "WHITE,KELVIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 35,
      "tfl": 0,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 19,
      "group": "GOOD"
    },
    {
      "name": "WILLIAMS,CHAVIS",
      "type": "Player",
      "isActive": "   ",
      "tackles": 17,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 4,
      "statPB": 1,
      "statGP": 14,
      "group": "GOOD"
    },
    {
      "name": "WILLIAMS,J",
      "type": "Player",
      "isActive": "   ",
      "tackles": 58,
      "tfl": 3,
      "sacks": 0,
      "breakUps": 4,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 1,
      "statPB": 0,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "WILLIAMS,JESSE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 57,
      "tfl": 10,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 7,
      "statPB": 1,
      "statGP": 23,
      "group": "GOOD"
    },
    {
      "name": "WILLIAMS,LESLIE",
      "type": "Player",
      "isActive": "   ",
      "tackles": 13,
      "tfl": 2,
      "sacks": 0,
      "breakUps": 0,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 0,
      "statPB": 1,
      "statGP": 11,
      "group": "GOOD"
    },
    {
      "name": "WILLIAMS,Q",
      "type": "Player",
      "isActive": "   ",
      "tackles": 80,
      "tfl": 27,
      "sacks": 0,
      "breakUps": 1,
      "statFF": 0,
      "statFR": 0,
      "statINT": 0,
      "statQBH": 14,
      "statPB": 0,
      "statGP": 21,
      "group": "GOOD"
    },
    {
      "name": "WILLIAMS,TIM",
      "type": "Player",
      "isActive": "   ",
      "tackles": 58,
      "tfl": 31,
      "sacks": 4,
      "breakUps": 3,
      "statFF": 2,
      "statFR": 1,
      "statINT": 0,
      "statQBH": 19,
      "statPB": 0,
      "statGP": 34,
      "group": "BEST"
    },
    {
      "name": "WILSON,MACK",
      "type": "Player",
      "isActive": "   ",
      "tackles": 119,
      "tfl": 8,
      "sacks": 0,
      "breakUps": 7,
      "statFF": 0,
      "statFR": 1,
      "statINT": 6,
      "statQBH": 11,
      "statPB": 0,
      "statGP": 34,
      "group": "BETTER"
    },
    {
      "name": "WOODALL,JUSTIN",
      "type": "Player",
      "isActive": "   ",
      "tackles": 98,
      "tfl": 5,
      "sacks": 0,
      "breakUps": 14,
      "statFF": 2,
      "statFR": 0,
      "statINT": 7,
      "statQBH": 1,
      "statPB": 1,
      "statGP": 31,
      "group": "BETTER"
    },
    {
      "name": "WORTHAM,C",
      "type": "Player",
      "isActive": "   ",
      "tackles": 264,
      "tfl": 11,
      "sacks": 0,
      "breakUps": 3,
      "statFF": 0,
      "statFR": 1,
      "statINT": 1,
      "statQBH": 12,
      "statPB": 0,
      "statGP": 43,
      "group": "GOOD"
    }
  ]
}
